package com.google.android.libraries.places.internal;

public enum zzeh {
    START,
    RESET,
    LOADING,
    TRY_AGAIN_PROGRESS_LOADING,
    SUCCESS_PREDICTIONS,
    FAILURE_NO_PREDICTIONS,
    FAILURE_PREDICTIONS,
    SUCCESS_SELECTION,
    FAILURE_SELECTION,
    FAILURE_UNRESOLVABLE
}
