package com.tt.miniapp.errorcode;

import com.huawei.hms.android.HwBuildEx;
import com.huawei.updatesdk.service.otaupdate.UpdateDialogStatusCode;

public enum ApiCode {
    GENERAL_OK(HwBuildEx.VersionCodes.CUR_DEVELOPMENT, "ok"),
    GENERAL_PARAM(UpdateDialogStatusCode.DISMISS, "invalid parameter"),
    GENERAL_JSON_ERROR(UpdateDialogStatusCode.SHOW, "internal error json"),
    GENERAL_FILE_CAN_NOT_READ(10003, "file can not read"),
    GENERAL_FILE_CAN_NOT_WRITE(10004, "file can not write"),
    GENERAL_SYSTEM_AUTH_DENY(10005, "system permission denied"),
    GENERAL_USER_AUTH_DENIED(10006, "user auth denied"),
    GENERAL_CANCEL(10007, "user cancel operation"),
    GENERAL_UNABLE(10008, "Invalid function"),
    GENERAL_BACKGROUND(10009, "app in background"),
    GENERAL_UNKONW_ERROR(10010, "unknown error"),
    REQUEST_INVALID_URL(20101, "invalid url"),
    REQUEST_INVALID_DOMAIN(20102, "invalid domain"),
    REQUEST_INVALID_METHOD(20103, "method is invalid"),
    REQUEST_EXCEED_OVER_TASK_COUNT(20104, "exceed max task count"),
    REQUEST_TIMEOUT(20105, "timeout"),
    REQUEST_ABORT(20106, "abort"),
    UPLOADFILE_INVALID_URL(20201, "Invalid url"),
    UPLOADFILE_INVALID_FILEPATH(20202, "Invalid filePath"),
    UPLOADFILE_INVALID_DOMAIN(20203, "invalid domain"),
    UPLOADFILE_FILE_EMPTY(20204, "file is empty"),
    UPLOADFILE_NAME_EMPTY(20205, "invalid name"),
    UPLOADFILE_ABORT(20206, "abort"),
    DOWNLOADFILE_INVALID_URL(20301, "invalid url"),
    DOWNLOADFILE_INVALID_DOMAIN(20302, "invalid domain"),
    DOWNLOADFILE_INVALID_METHOD(20303, "invalid method"),
    DOWNLOADFILE_FILE_NOT_EXIST(20304, "no such file or directory"),
    DOWNLOADFILE_OVER_LIMIT(20305, "user dir saved file size limit exceeded"),
    DOWNLOADFILE_ABORT(20306, "abort"),
    CREATESOCKETTASK_INVALID_URL(20401, ""),
    CONNECTSOCKET_INVALID_URL(20401, "invalid url"),
    CONNECTSOCKET_INVALID_DOMAIN(20402, "invalid domain"),
    OPERATESOCKETTASK_SOCKET_NO_CREATE_SOCKETID(20403, ""),
    CONNECTSOCKET_SOCKET_NO_CREATE_SOCKETID(20403, "socket no create socketId"),
    OPERATESOCKETTASK_ILLEGAL_OPERATIONTYPE(20404, ""),
    CONNECTSOCKET_ILLEGAL_OPERATIONTYPE(20404, "illegal operationType"),
    CONNECTSOCKET_SEND_ERROR(20405, "send error"),
    SAVEIMAGETOPHOTOSALBUM_INVALID_FILEPATH(30201, "invalid filePath"),
    SAVEIMAGETOPHOTOSALBUM_INVALID_IMAGE_DATA(30202, "invalid imageData"),
    SAVEIMAGETOPHOTOSALBUM_PATH_EMPTY(30203, "selected path cannot be empty"),
    PREVIEWIMAGE_INVALID_URLS(30301, "invalid urls"),
    PREVIEWIMAGE_URLS_EXCLUSIVE(30302, "urls and requests is mutually exclusive"),
    PREVIEWIMAGE_INVALID_HEADER(30303, "invalid header"),
    PREVIEWIMAGE_URL_EMPTY(30304, "url is empty"),
    PREVIEWIMAGE_INVALID_METHOD(30305, "invalid method"),
    COMPRESSIMAGE_INVALID_SRC(30401, "invalid src"),
    COMPRESSIMAGE_DECODE_FAIL(30402, "decode image fail"),
    COMPRESSIMAGE_COMPRESS_FAIL(30403, "compress image fail"),
    COMPRESSIMAGE_WRITE_IMAGE_FAIL(30404, "write image to file fail"),
    GETIMAGEINFO_INVALID_SRC(30501, "invalid src"),
    GETIMAGEINFO_FILE_NOT_EXIST(30502, "no such file or directory "),
    GETRECORDERMANAGER_TYPE_INVALID(30601, "invalid operationType"),
    CHOOSEVIDEO_OVER_MAX_DURATION(30801, "over the maxDuration"),
    SAVEVIDEOTOPHOTOSALBUM_FILE_PATH_EMPTY(30901, "filePath is empty"),
    SAVEVIDEOTOPHOTOSALBUM_FILE_NOT_EXIST(30902, "filePath not exist"),
    SAVEVIDEOTOPHOTOSALBUM_FILE_NOT_VIDOE(30903, "file is not video"),
    STARTDEVICECREDENTIAL_PASSWORD_NOT_SET(40000, "password not set"),
    STARTDEVICECREDENTIAL_USER_CANCEL(40001, "user cancel"),
    STARTDEVICECREDENTIAL_UNLOCK_FAIL(40002, "unlock fail"),
    STARTDEVICECREDENTIAL_AUTHCONTENT_EMPTY(40003, "authContent is empty"),
    STARTPASSWORDVERIFY_USER_CANCEL(40101, "user canceled, security verification failed."),
    STARTPASSWORDVERIFY_PASSWORD_ERROR(40102, "incorrect password, security verification failed."),
    STARTPASSWORDVERIFY_RETRY_TIME_LIMIT(40103, "incorrect password is entered too many times, security verification failed."),
    LOGIN_NOT_RETRY(40501, "logining, not retrys"),
    LOGIN_FAIL(40502, "login failed"),
    CHECKSESSION_INVALID_SESSION(40601, "invalid session "),
    GETUSERINFO_NOT_LOGIN(40701, "not login"),
    GETUSERINFO_GET_USER_INFO_FAIL(40702, "get user info failed"),
    ENTERPROFILE_GET_USERID_FAIL(40801, "Get userId failed"),
    AUTHORIZE_INVALID_SCOPE(41201, "invalid scope"),
    AUTHORIZE_AUTH_DENY(41202, "auth deny"),
    ENTERCHAT_GET_CHATID_FAIL(41301, "get chatId from openChatId fail"),
    ENTERCHAT_ID_EMPTY(41302, "openChatId and chatId is both null"),
    CHOOSECONTACT_OPEN_CONTACT_FAIL(41401, "open contact list failed"),
    CHOOSECONTACT_GET_OPENID_FAIL(41402, "get openId fail"),
    CHOOSECONTACT_GET_USER_INFO_FAIL(41403, "get user info fail"),
    CHOOSECHAT_GET_CHATINFO_FAIL(41501, ""),
    CHOOSECHAT_GET_OPENCHATID_FAIL(41502, ""),
    SHAREAPPMESSAGEDIRECTLY_NOT_SUPPORT_FEED_MODE(41810, ""),
    SHOWSHAREMENU_INVALID_TYPE(41901, "invalid type"),
    SHOWSHAREMENU_FORBIDDEN_IN_BLACKLIST(41902, "forbidden in blackList"),
    ENTERBOT_BOTID_IS_EMPTY(42001, ""),
    GETKAINFO_APP_NOT_IN_OKLIST(42101, "app not in oklist"),
    TRIGGERCHECKUPDATE_GET_ONLINE_VERSION_FAIL(42201, ""),
    TRIGGERCHECKUPDATE_NO_NEED_UPDATE(42202, ""),
    TRIGGERCHECKUPDATE_INSTALL_PACKAGE_FAIL(42203, ""),
    GETBLOCKACTIONSOURCEDETAIL_CODE_EMPTY(42301, "triggerCode is empty"),
    GETBLOCKACTIONSOURCEDETAIL_CODE_INVALID(42302, "invalid triggerCode"),
    GETBLOCKACTIONSOURCEDETAIL_PLATFORM_SESSION_EMPTY(42303, "not login"),
    GETBLOCKACTIONSOURCEDETAIL_GET_BLOCK_ACTION_FAIL(42304, "get block action failed"),
    GETBLOCKACTIONSOURCEDETAIL_SERVICE_NOT_VALID(42305, "service is not valid"),
    GETBLOCKACTIONSOURCEDETAIL_RESULT_IS_EMPTY(42306, "result is empty"),
    GETBLOCKACTIONSOURCEDETAIL_INVALID_APP_ID(42307, ""),
    SENDMESSAGECARD_CODE_AND_ID_NEED(42401, ""),
    SENDMESSAGECARD_ID_COUNT_EXCEED_TEN(42402, ""),
    SENDMESSAGECARD_CARD_CONTENT_IS_EMPTY(42403, ""),
    SENDMESSAGECARD_FAIL_CONVERT_TO_PB(42404, ""),
    SENDMESSAGECARD_TRIGGER_CODE_IS_INVALID(42405, ""),
    SENDMESSAGECARD_PART_OF_ID_INVALID(42406, ""),
    UPDATEBADGE_NONEXISTENT_BADGE(42501, "nonexistent badge"),
    REPORTBADGE_NONEXISTENT_BADGE(42601, "nonexistent badge"),
    CALLLIGHTSERVICE_CLOUD_SERVICE_REQUEST_FAIL(42701, "cloud service request fail"),
    CALLLIGHTSERVICE_RESOURCE_NOT_FOUND(42702, "resource not found"),
    GETTENANTAPPSCOPES_NOT_VISIBLE(42801, "app is not visible"),
    GETTENANTAPPSCOPES_NOT_INSTALLED(42802, "app is not installed"),
    SAVEFILE_INVALID_TEMPFILEPATH(50101, "invalid tempFilePath"),
    SAVEFILE_INVALID_FILEPATH(50102, "invalid filePath"),
    SAVEFILE_LIMIT_EXCEEDED(50103, "user dir saved file size limit exceeded"),
    SAVEFILE_MOVE_FILE_FAIL(50104, "move file fail"),
    OPENDOCUMENT_FILETYPE_NOT_SUPPORTED(50401, "filetype not supported"),
    OPENDOCUMENT_INVALID_FILEPATH(50402, "invalid filePath"),
    OPENDOCUMENT_SPACEFILE_INVALID(50403, "spaceFile filePath does not support"),
    OPENDOCUMENT_FILE_NOT_EXIST(50404, "file not exist"),
    OPENDOCUMENT_OPEN_FILE_FAIL(50405, "open file fail"),
    SAVEFILEAS_EMPTY_FILEPATH(50501, ""),
    SAVEFILEAS_INVALID_FIELPATH(50502, ""),
    SAVEFILEAS_COPY_FAIL(50503, ""),
    REMOVESAVEDFILE_FILE_CANNOT_ACCESS(50601, "file is not in user or temp"),
    REMOVESAVEDFILE_FILE_NOT_EXIST(50602, "file not exist"),
    REMOVESAVEDFILE_FILE_IS_DIR(50603, "file is dir cannot delete dir"),
    REMOVESAVEDFILE_FILE_DELETE_FAILED(50604, "file delete failed"),
    GETSTORAGE_KEY_ILLEGAL(60101, "param.key should pass String"),
    GETSTORAGE_KEY_NOT_FOUND(60102, "key not found"),
    SETSTORAGE_KEY_ILLEGAL(60301, "key is illegal"),
    SETSTORAGE_ITEM_STORAGE_EXCEED(60302, "exceed storage item max size"),
    SETSTORAGE_TOTAL_STORAGE_EXCEED(60303, "total storage size exceed "),
    REMOVESTORAGE_KEY_ILLEGAL(60501, "key is illegal"),
    REMOVESTORAGE_KEY_NOT_FOUND(60502, "key not found"),
    CLEARSTORAGE_CLEAR_FAIL(60701, "clear storage fail"),
    GETENVVARIABLE_GET_CONFIG_FAIL(60801, "get config fail"),
    GETLOCATION_UNABLE_ACCESS_LOCATION(70101, "unable access location"),
    GETLOCATION_INVALID_RESULT(70102, "invalid latitude or longitude"),
    GETLOCATION_LOCATION_FAIL(70103, "location fail"),
    OPENLOCATION_INVALID_LATITUDE(70201, "invalid latitude"),
    OPENLOCATION_INVALID_LONGITUDE(70202, "invalid longitude"),
    OPENLOCATION_INVALID_SCALE(70205, "invalid scale"),
    GETCONNECTEDWIFI_WIFI_NOT_TURNED_ON(70902, "wifi not turned on"),
    GETCONNECTEDWIFI_INVALID_SSID(70903, "invalid SSID"),
    GETWIFILIST_WIFI_NOT_TURNED_ON(71102, "wifi not turned on"),
    GETWIFILIST_GPS_NOT_TURNED_ON(71103, "gps not turned on"),
    STARTACCELEROMETER_ACCELEROMETER_NOT_SUPPORT(71401, "not support accelerometers"),
    STARTACCELEROMETER_ACCELEROMETER_IS_RUNNING(71402, "Accelerometer is running"),
    OPERATECOMPASS_COMPASS_NOT_SUPPORT(71501, "not support compass"),
    MAKEPHONECALL_INVALID_PHONE_NUMBER(72001, "invalid phone number"),
    SCANCODE_SCAN_CODE_RUNNING(72101, "scan code running"),
    SETCLIPBOARDDATA_PARAMS_NOT_STRING(72301, ""),
    PRINT_EMPTY_URL(72901, ""),
    PRINT_PROTOCOL_FAIL(72902, ""),
    PRINT_DEVICE_ERROR(72903, ""),
    SHOWTOAST_INVALID_TITLE(80101, "invalid title"),
    SHOWMODAL_INVALID_MODAL(80501, "invalid title and content"),
    SHOWACTIONSHEET_EMPTY_ITEM(80601, "empty item list param"),
    SHOWACTIONSHEET_LIST_OVER_LIMIT(80602, "item list count limited"),
    SETNAVIGATIONBARCOLOR_INVALID_FRONT_COLOR(80801, "invalid front clolor param"),
    SETNAVIGATIONBARCOLOR_INVALID_BACKGROUND_COLOR(80802, "invalid background color param"),
    SETTABBARBADGE_NO_TAB(81201, ""),
    SETTABBARBADGE_TEXT_EMPTY(81202, "invalid text param"),
    SETTABBARBADGE_INDEX_IS_NOT_NUMBER(81203, "params.index is not number"),
    SETTABBARBADGE_INDEX_ERROR(81204, "tab item index out of bounds"),
    SHOWTABBARREDDOT_NO_TAB(81301, "no tabBar in the current app"),
    SHOWTABBARREDDOT_INDEX_IS_NOT_NUMBER(81302, ""),
    SHOWTABBARREDDOT_INDEX_ERROR(81303, "tab item index out of bounds"),
    REMOVETABBARBADGE_NO_TAB(81401, "no tabBar in the current app"),
    REMOVETABBARBADGE_INDEX_IS_NOT_NUMBER(81402, "params.index is not number"),
    REMOVETABBARBADGE_INDEX_ERROR(81403, "tab item index out of bounds"),
    HIDETABBARREDDOT_NO_TAB(81501, "no tabBar in the current app"),
    HIDETABBARREDDOT_INDEX_IS_NOT_NUMBER(81502, "params.index is not number"),
    HIDETABBARREDDOT_INDEX_ERROR(81503, "tab item index out of bounds"),
    HIDETABBAR_NO_TAB(81601, "no tabBar in the current app"),
    SHOWTABBAR_NO_TAB(81701, "no tabBar in the current app"),
    SETTABBARITEM_NO_TAB(81801, "no tabBar in the current app"),
    SETTABBARITEM_INDEX_IS_NOT_NUMBER(81802, "params.index is not number"),
    SETTABBARITEM_INDEX_ERROR(81803, "tab item index out of bounds"),
    SETTABBARITEM_ICON_NOT_FOUND(81804, "icon path not found"),
    SETTABBARITEM_SELECTED_ICON_NOT_FOUND(81805, "selected icon path not found"),
    SETTABBARSTYLE_NO_TAB(81901, "no tabBar in the current app"),
    NAVIGATETO_NAVIGATE_TAB_PAGE(90101, "only navigate to non-tab page"),
    NAVIGATETO_OVER_PAGE_COUNT_LIMIT(90102, "page count limited"),
    NAVIGATETO_PAGE_NOT_EXIST(90103, "target page not exist"),
    REDIRECTTO_REDIRECT_TAB_PAGE(90201, "only redirect to non-tab page"),
    REDIRECTTO_PAGE_NOT_EXIST(90202, "target page not exist"),
    SWITCHTAB_SWITCH_NON_TAB(90301, "target page not tab"),
    SWITCHTAB_PAGE_NOT_EXIST(90302, "target page not exist"),
    RELAUNCH_PAGE_NOT_EXIST(90501, "target page not exist\t"),
    OPENSCHEMA_EMPTY_SCHEMA(90601, "empty schema param"),
    OPENSCHEMA_ILLEGAL_SCHEMA(90602, "illegal schema param"),
    OPENSCHEMA_NOT_WHITE(90603, "not in the white list"),
    OPENSCHEMA_NOT_SUPPORTED_MODE(90604, "current mode not supported"),
    OPENSCHEMA_OPEN_FAILED(90605, "open schema failed"),
    ONCHATBADGECHANGE_SAME_OPENCHATID(402001, ""),
    ONCHATBADGECHANGE_GET_CHATID_FAILED(402002, ""),
    GETCHATINFO_NO_AUTH(402101, ""),
    OFFCHATBADGECHANGE_OFF_SAME_ID(402101, ""),
    GETCHATINFO_GET_FAIL_OPENCHATID(402102, ""),
    OFFCHATBADGECHANGE_GET_CHATID_FAILED(402102, ""),
    GETCHATINFO_EMPTY_OPENCHATID(402103, ""),
    GETCHATINFO_INVALID_CHATID(402104, ""),
    END(-1, "end");
    
    public int code;
    public String msg;

    private ApiCode(int i, String str) {
        this.code = i;
        this.msg = str;
    }
}
