package com.bytedance.ee.bear;

public enum DocPluginLevel {
    EditModeSwitchButton,
    AnnounceButton,
    BlockEditMenu,
    Toolbar,
    ToolbarV2,
    SheetToolbarV2,
    InsertNewBlock,
    SmallLoading,
    Translate,
    Structure,
    At,
    DiyIcon,
    CustomHeader,
    Search,
    BitableCard,
    FloatActionButton,
    BitableFloatActionButton,
    ImgViewer,
    Reminder,
    SheetReminder,
    Snapshot,
    Comment,
    CommentImageViewer,
    CodeBlock,
    Cover,
    PartialLoading
}
