package com.serenegiant.usb;

import android.util.SparseArray;
import com.huawei.hms.framework.common.ExceptionCode;
import com.huawei.hms.support.api.entity.auth.AuthCode;

class USBVendorId {
    private static final SparseArray<String> IDS;

    USBVendorId() {
    }

    static {
        SparseArray<String> sparseArray = new SparseArray<>();
        IDS = sparseArray;
        sparseArray.put(10006, "YUEN DA ELECTRONIC PRODUCTS FACTORY");
        sparseArray.put(10013, "Gionee Communication Equipment Co., Ltd. ShenZhen");
        sparseArray.put(10022, "Universal Electronics Inc. (dba: TVIEW)");
        sparseArray.put(1003, "Atmel Corporation");
        sparseArray.put(1006, "Mitsumi");
        sparseArray.put(1008, "HP Inc.");
        sparseArray.put(10112, "M31 Technology Corp.");
        sparseArray.put(10113, "Liteconn Co., Ltd.");
        sparseArray.put(10121, "Suzhou WEIJU Electronics Technology Co., Ltd.");
        sparseArray.put(10144, "Mondokey Limited");
        sparseArray.put(10149, "Advantest Corporation");
        sparseArray.put(10150, "iRobot Corporation");
        sparseArray.put(1020, "Elitegroup Computer Systems");
        sparseArray.put(1021, "Xilinx Inc.");
        sparseArray.put(10226, "Sibridge Tech.");
        sparseArray.put(1026, "ALi Corporation");
        sparseArray.put(1027, "Future Technology Devices International Limited");
        sparseArray.put(10275, "Dongguan Jiumutong Industry Co., Ltd.");
        sparseArray.put(10289, "Power Integrations");
        sparseArray.put(10291, "Oculus VR, Inc.");
        sparseArray.put(10300, "HIGH TEK HARNESS ENTERPRISE CO., LTD.");
        sparseArray.put(10316, "Full in Hope Co., Ltd.");
        sparseArray.put(1032, "Quanta Computer Inc.");
        sparseArray.put(10329, "Viconn Technology (HK) Co., Ltd.");
        sparseArray.put(1033, "NEC Corporation");
        sparseArray.put(1035, "Weltrend Semiconductor");
        sparseArray.put(1037, "VIA Technologies, Inc.");
        sparseArray.put(10374, "Seeed Technology Co., Ltd.");
        sparseArray.put(10375, "Specwerkz");
        sparseArray.put(1038, "MCCI Corporation");
        sparseArray.put(10398, "Esselte Leitz GmbH & Co. KG");
        sparseArray.put(10406, "E-SEEK Inc.");
        sparseArray.put(1041, "BUFFALO INC.");
        sparseArray.put(10423, "Pleora Technologies Inc.");
        sparseArray.put(10431, "Vitetech Int'l Co., Ltd.");
        sparseArray.put(1044, "Giga-Byte Technology Co., Ltd.");
        sparseArray.put(10446, "Changzhou Shi Wujin Miqi East Electronic Co., Ltd.");
        sparseArray.put(10457, "Shenzhen Ourconn Technology Co., Ltd.");
        sparseArray.put(10458, "G.SKILL Int'l Enterprice Co., Ltd.");
        sparseArray.put(1046, "Nuvoton Technology Corp.");
        sparseArray.put(10466, "Surplus Electronic Technology Co., Ltd.");
        sparseArray.put(10470, "BIAMP SYSTEMS");
        sparseArray.put(10509, "IBCONN Technologies (Shenzhen) Co., Ltd.");
        sparseArray.put(10510, "Fugoo Inc.");
        sparseArray.put(10519, "Pan Xin Precision Electronics Co., Ltd.");
        sparseArray.put(10530, "Dongguan Digi-in Digital Technology Co., Ltd.");
        sparseArray.put(1054, "Creative Labs");
        sparseArray.put(10540, "GENUSION, Inc.");
        sparseArray.put(10544, "Ineda Systems Inc.");
        sparseArray.put(10545, "Jolla Ltd.");
        sparseArray.put(10546, "Peraso Technologies, Inc.");
        sparseArray.put(10549, "Nanjing Magewell Electronics Co., Ltd.");
        sparseArray.put(10560, "Shenzhen Yiwanda Electronics Co., Ltd.");
        sparseArray.put(1057, "Nokia Corporation");
        sparseArray.put(10575, "Dollar Connection Ltd.");
        sparseArray.put(10595, "BIO-key International, Inc.");
        sparseArray.put(1060, "Microchip-SMSC");
        sparseArray.put(10603, "Xacti Corporation");
        sparseArray.put(10615, "Shenzhen Zowee Technology Co., Ltd.");
        sparseArray.put(10643, "ADPlaus Technology Limited");
        sparseArray.put(10646, "Unwired Technology");
        sparseArray.put(1065, "Cirrus Logic Inc.");
        sparseArray.put(10657, "Union Electric Plug & Connector Corp.");
        sparseArray.put(10674, "Canova Tech");
        sparseArray.put(10685, "Silicon Works");
        sparseArray.put(10695, "HANRICO ANFU ELECTRONICS CO., LTD.");
        sparseArray.put(10700, "Kodak Alaris");
        sparseArray.put(10702, "JGR Optics Inc.");
        sparseArray.put(10703, "Richtek Technology Corporation");
        sparseArray.put(10705, "Binatone Electronics Int. Ltd.");
        sparseArray.put(1071, "Molex Inc.");
        sparseArray.put(10715, "Shenzhen iBoard Technology Co., Ltd.");
        sparseArray.put(10719, "SMIT(HK) Limited");
        sparseArray.put(1072, "Fujitsu Component Limited");
        sparseArray.put(10725, "Dongguan Kechenda Electronic Technology Co., Ltd.");
        sparseArray.put(10726, "Fengshun Peiying Electro-Acoustic Co., Ltd.");
        sparseArray.put(10744, "MD ELEKTRONIK GmbH");
        sparseArray.put(10749, "Bad Elf, LLC");
        sparseArray.put(10770, "Vreo Limited");
        sparseArray.put(10772, "Kanex");
        sparseArray.put(10781, "Oxford Nanopore Technologies");
        sparseArray.put(10782, "Obsidian Technology");
        sparseArray.put(10783, "Lucent Trans Electronics Co., Ltd.");
        sparseArray.put(10784, "GUOGUANG GROUP CO., LTD.");
        sparseArray.put(10788, "CNPLUS");
        sparseArray.put(10789, "Fourstar Group");
        sparseArray.put(10790, "Tragant International Co., Ltd.");
        sparseArray.put(10791, "DongGuan LianGang Optoelectronic Technology Co., Ltd.");
        sparseArray.put(10797, "Atrust Computer Corp.");
        sparseArray.put(10798, "VIA Alliance Semiconductor Co., Ltd.");
        sparseArray.put(10799, "BSUN Electronics Co., Ltd.");
        sparseArray.put(1080, "Advanced Micro Devices");
        sparseArray.put(10807, "RTD Embedded Technologies, Inc.");
        sparseArray.put(10816, "Shenzhen Choseal Industrial Co., Ltd.");
        sparseArray.put(10817, "Canyon Semiconductor");
        sparseArray.put(10818, "Spectra7 Microsystems Corp.");
        sparseArray.put(10821, "Meizu Technology Co., Ltd.");
        sparseArray.put(10822, "Hubei Yingtong Telecommunication Cable Inc.");
        sparseArray.put(10829, "Wilder Technologies");
        sparseArray.put(10837, "Diodes Inc.");
        sparseArray.put(10846, "DuPont");
        sparseArray.put(1085, "Lexmark International Inc.");
        sparseArray.put(10852, "Zhejiang Songcheng Electronics Co., Ltd.");
        sparseArray.put(10859, "VSN Mobil");
        sparseArray.put(10875, "Bellwether Electronic Corp.");
        sparseArray.put(10878, "VAIO Corporation");
        sparseArray.put(10879, "Perixx Computer GmbH");
        sparseArray.put(10885, "HANK ELECTRONICS CO., LTD");
        sparseArray.put(10892, "Sonnet Technologies, Inc.");
        sparseArray.put(10893, "Keysight Technologies Inc.");
        sparseArray.put(10895, "Manutronics Vietnam Joint Stock Company");
        sparseArray.put(10900, "G2 Touch Co., Ltd.");
        sparseArray.put(10902, "Micromax Informatics Ltd");
        sparseArray.put(10910, "SEIKO SOLUTIONS Inc.");
        sparseArray.put(10912, "Casco Products Corp.");
        sparseArray.put(10922, "Virtium Technology, Inc.");
        sparseArray.put(10923, "Field and Company LLC, dba Leef USA");
        sparseArray.put(10928, "GM Global Technology Operations LLC");
        sparseArray.put(10931, "Key Asic Inc.");
        sparseArray.put(10943, "Revolabs, Inc.");
        sparseArray.put(10945, "Lattice Semiconductor Corp");
        sparseArray.put(10947, "Foshan Nanhai Saga Audio Equipment Co., Ltd.");
        sparseArray.put(10957, "Silergy Corp.");
        sparseArray.put(10963, "Shenzhen Hali-Power Industrial Co., Ltd.");
        sparseArray.put(10971, "I-PEX (Dai-ichi Seiko)");
        sparseArray.put(10973, "SEE-PLUS INDUSTRIAL LTD.");
        sparseArray.put(10990, "Adapt-IP Company");
        sparseArray.put(10997, "Libratone A/S");
        sparseArray.put(10999, "Shenzhen Hazens Automotive Electronics (SZ) Co., Ltd.");
        sparseArray.put(11000, "Jiangsu Toppower Automotive Electronics Co., Ltd.");
        sparseArray.put(11001, "Drapho Electronics Technology Co., Ltd.");
        sparseArray.put(ExceptionCode.NETWORK_IO_EXCEPTION, "Alps Electric Co., Ltd.");
        sparseArray.put(11022, "Le Shi Zhi Xin Electronic Technology (Tian Jin) Limited");
        sparseArray.put(11024, "Cardiac Insight, Inc.");
        sparseArray.put(11028, "EverPro Technologies Company, Ltd.");
        sparseArray.put(11029, "Rosenberger Hochfrequenztechnik");
        sparseArray.put(11035, "Dongguan City Sanji Electronics Co., Ltd.");
        sparseArray.put(11037, "Lintes Technology Co., Ltd.");
        sparseArray.put(11039, "KinnexA, Inc.");
        sparseArray.put(11042, "Metra Electronics Corp.");
        sparseArray.put(11044, "KeepKey, LLC");
        sparseArray.put(11047, "FluxData Incorporated");
        sparseArray.put(1105, "Texas Instruments");
        sparseArray.put(11061, "Assem Technology Co., Ltd.");
        sparseArray.put(11062, "Dongguan City Jianghan Electronics Co., Ltd.");
        sparseArray.put(11063, "Huizhou Desay SV Automotive Co., Ltd.");
        sparseArray.put(11064, "Ningbo Rixing Electronics Co., Ltd.");
        sparseArray.put(11069, "GuangDong YuanFeng Automotive Electroics Co., Ltd.");
        sparseArray.put(11080, "Sounding Audio Industrial Limited");
        sparseArray.put(11082, "Yueqing Huaxin Electronic Co., Ltd.");
        sparseArray.put(11098, "Universal Audio, Inc.");
        sparseArray.put(11111, "Lifesize, Inc.");
        sparseArray.put(11123, "Pioneer DJ Corporation");
        sparseArray.put(11124, "Embedded Intelligence, Inc.");
        sparseArray.put(11125, "New Matter");
        sparseArray.put(11126, "Shanghai Wingtech Electronic Technology Co., Ltd.");
        sparseArray.put(11127, "Epiphan Systems Inc.");
        sparseArray.put(11130, "Spin Master Far East Ltd.");
        sparseArray.put(11131, "Gigaset Digital Technology (Shenzhen) Co., Ltd.");
        sparseArray.put(11132, "Noveltek Semiconductor Corp.");
        sparseArray.put(11139, "Silicon Line GmbH");
        sparseArray.put(11140, "Ever Win International Corp.");
        sparseArray.put(11144, "Socionext Inc.");
        sparseArray.put(11145, "Ugreen Group Limited");
        sparseArray.put(11146, "Shanghai Pateo Electronic Equipment Mfg. Co., Ltd.");
        sparseArray.put(1115, "Renesas Electronics Corp.");
        sparseArray.put(11154, "i-BLADES, Inc.");
        sparseArray.put(11155, "Altia Systems Inc.");
        sparseArray.put(11156, "ShenZhen Baoyuanda Electronics Co., Ltd.");
        sparseArray.put(11157, "iST - Integrated Service Technology Inc.");
        sparseArray.put(11158, "HYUNDAI MOBIS Co., Ltd.");
        sparseArray.put(11161, "360fly, Inc.");
        sparseArray.put(11162, "HUIZHOU CHENG SHUO HARDWARE PLASTIC CO., LTD.");
        sparseArray.put(11163, "Zhongshan Aute Electronics Technology Co., Ltd.");
        sparseArray.put(11164, "Guangdong King Link Industrial Co., Ltd.");
        sparseArray.put(11167, "Scietera Technologies, Inc.");
        sparseArray.put(11168, "InVue Security Products");
        sparseArray.put(11169, "I-Sheng Electric Wire & Cable Co., Ltd.");
        sparseArray.put(11170, "China Daheng Group Inc Beijing Image Vision Tech Branch");
        sparseArray.put(11171, "Shenzhen FeiTianXia Technology Ltd.");
        sparseArray.put(11172, "Shenzhen HengJia New Energy Auto Part Co., Ltd.");
        sparseArray.put(11175, "77 Elektronika Kft.");
        sparseArray.put(11176, "YUDU EASON ELECTRONIC CO., LTD.");
        sparseArray.put(1118, "Microsoft Corporation");
        sparseArray.put(11181, "XIN JI (SHENZHEN) COMPUTER PARTS CO., LTD.");
        sparseArray.put(11189, "Silk ID Systems");
        sparseArray.put(11190, "3D Imaging & Simulations Corp. (3DISC)");
        sparseArray.put(11191, "Dongguan ChengXiang Industrial Co., Ltd.");
        sparseArray.put(11192, "OCC (Zhuhai) Electronic Co., Ltd.");
        sparseArray.put(11194, "Sinseader Electronic Co., Ltd.");
        sparseArray.put(11195, "DONGGUAN YELLOWKNIFE Industrial Co., Ltd.");
        sparseArray.put(11197, "RF Creations Ltd.");
        sparseArray.put(11198, "Chengyi Semiconductors (Shanghai) Co., Ltd.");
        sparseArray.put(11199, "Shenzhen Shinning Electronic Co., Ltd.");
        sparseArray.put(11200, "Shenzhen WFD Electronics Co., Ltd.");
        sparseArray.put(11201, "Dongguan Sino Syncs Industrial Co., Ltd.");
        sparseArray.put(11202, "JNTC Co., Ltd.");
        sparseArray.put(11208, "DONGGUAN POLIXIN ELECTRIC CO., LTD.");
        sparseArray.put(11209, "Tama Electric (Suzhou) Co., Ltd.");
        sparseArray.put(1121, "Primax Electronics");
        sparseArray.put(11210, "Exvision, Inc.");
        sparseArray.put(11216, "mophie, LLC");
        sparseArray.put(11219, "Dongguan ULT-unite electronic technology co., LTD");
        sparseArray.put(11220, "JL Audio, Inc.");
        sparseArray.put(11221, "Cable Matters Inc.");
        sparseArray.put(11222, "CoroWare, Inc.");
        sparseArray.put(11229, "Charm Sciences Inc.");
        sparseArray.put(1123, "EATON");
        sparseArray.put(11230, "Pickering Interfaces Limited");
        sparseArray.put(11231, "Hangzhou Hikvision Digital Technology Co., Ltd.");
        sparseArray.put(11232, "FULLINK ELECTRONICS TECHNOLOGY (SZ) LTD");
        sparseArray.put(11233, "AutoChips Inc.");
        sparseArray.put(11234, "Electric Connector Technology Co., Ltd.");
        sparseArray.put(11237, "LELTEK");
        sparseArray.put(11238, "Dongguan KaiWin Electronics Co., Ltd.");
        sparseArray.put(11239, "BEFS Co., Ltd.");
        sparseArray.put(11240, "Archisite, Inc.");
        sparseArray.put(11241, "Magneti Marelli S.p.A Electr BL");
        sparseArray.put(11246, "Ventev Mobile");
        sparseArray.put(11247, "Quanta Storage Inc.");
        sparseArray.put(11248, "Tech-Top Technology Limited");
        sparseArray.put(11253, "Shenzhen YOOBAO Technology Co., Ltd.");
        sparseArray.put(11254, "Shenzhen Sinotek Technology Co., Ltd.");
        sparseArray.put(11255, "KEYW");
        sparseArray.put(11256, "Visual Land Inc.");
        sparseArray.put(11264, "MEEM SL Ltd");
        sparseArray.put(11265, "Dongguan Arin Electronics Technology Co., Ltd.");
        sparseArray.put(11266, "DongGuan City JianNuo Electronics Co., Ltd.");
        sparseArray.put(11268, "Shenzhen XOX Electronics Co., Ltd.");
        sparseArray.put(11269, "Protop International Inc.");
        sparseArray.put(11270, "Microsemi Semiconductor (US) Inc.");
        sparseArray.put(11271, "Webcloak LLC");
        sparseArray.put(11272, "INVECAS INC.");
        sparseArray.put(11274, "ATANS Technology Inc.");
        sparseArray.put(11275, "Triple Win Precision Technology Co., Ltd.");
        sparseArray.put(11276, "IC Realtech");
        sparseArray.put(11277, "Embrava Pty Ltd");
        sparseArray.put(1128, "Wieson Technologies Co., Ltd.");
        sparseArray.put(11280, "Sinotronics Co., Ltd.");
        sparseArray.put(11281, "ALLBEST ELECTRONICS TECHNOLOGY CO., LTD.");
        sparseArray.put(11282, "Shenzhen Xin Kai Feng Electronics Factory");
        sparseArray.put(11283, "MOST WELL Technology Corp.");
        sparseArray.put(11284, "Buffalo Memory Co., Ltd.");
        sparseArray.put(11285, "Xentris Wireless");
        sparseArray.put(11286, "Priferential Accessories Ltd");
        sparseArray.put(11289, "Sunlike Technology Co., Ltd.");
        sparseArray.put(11290, "Young Fast Optoelectronics Co., Ltd.");
        sparseArray.put(11291, "ISAW Camera Inc");
        sparseArray.put(11298, "Qanba USA, LLC");
        sparseArray.put(11299, "Super Micro Computer Inc.");
        sparseArray.put(11302, "Micromax International Corporation");
        sparseArray.put(11304, "Granite River Labs Japan Ltd.");
        sparseArray.put(11305, "Coagent Enterprise Limited");
        sparseArray.put(11306, "LEIA Inc.");
        sparseArray.put(11309, "Shenzhen Ebull Technology Limited");
        sparseArray.put(1131, "American Megatrends");
        sparseArray.put(11310, "Hualun Technology Co., Ltd.");
        sparseArray.put(11311, "Sensel, Inc.");
        sparseArray.put(11319, "Shenzhen Adition Audio Science & Technology Co., Ltd.");
        sparseArray.put(11320, "Goldenconn Electronics Technology (Suzhou) Co., Ltd.");
        sparseArray.put(11321, "JIB Electronics Technology Co., Ltd.");
        sparseArray.put(11322, "Changzhou Shinco Automotive Electronics Co., Ltd.");
        sparseArray.put(11323, "Shenzhen Hangsheng Electronics Corp., Ltd.");
        sparseArray.put(11324, "Beartooth Radio, Inc.");
        sparseArray.put(11325, "Audience, A Knowles Company");
        sparseArray.put(11327, "Nextbit Systems, Inc.");
        sparseArray.put(11328, "Leadtrend");
        sparseArray.put(11329, "Adaptertek Technology Co., Ltd.");
        sparseArray.put(1133, "Logitech Inc.");
        sparseArray.put(11330, "Feature Integration Technology Inc.");
        sparseArray.put(11331, "Avegant Corporation");
        sparseArray.put(11335, "Chunghsin International Electronics Co., Ltd.");
        sparseArray.put(11336, "Delphi Electrical Centers (Shanghai) Co., Ltd.");
        sparseArray.put(11341, "VVETEK DOO");
        sparseArray.put(11347, "Huizhou Foryou General Electronics Co., Ltd.");
        sparseArray.put(11348, "LifeWatch Technologies Ltd.");
        sparseArray.put(11349, "Magicleap");
        sparseArray.put(11355, "Dongguan City Shenglan Electronics Co., LTD.");
        sparseArray.put(11356, "Neusoft Corporation");
        sparseArray.put(11357, "SIP Simya Electronics Technology Co., Ltd.");
        sparseArray.put(11358, "GNSD Automotive Co., Ltd.");
        sparseArray.put(11359, "YOODS Co., Ltd.");
        sparseArray.put(11360, "Sirin Mobile Technologies AG");
        sparseArray.put(11361, "Jadmam Corporation dba: Boytone");
        sparseArray.put(11373, "Gibson Innovations");
        sparseArray.put(11374, "Shen Zhen Xian Shuo Technology Co. LTD");
        sparseArray.put(11375, "PST Eletronica LTDA");
        sparseArray.put(11376, "PERI, Inc.");
        sparseArray.put(11377, "Bozhou BoTong Information Technology Co., Ltd.");
        sparseArray.put(11383, "Profindustry GmbH");
        sparseArray.put(11384, "BRAGI GmbH");
        sparseArray.put(11385, "WAWGD, Inc. (DBA: Foresight Sports)");
        sparseArray.put(11390, "Dongguan Allpass Electronic Co., Ltd.");
        sparseArray.put(11391, "SHENZHEN D-VITEC INDUSTRIAL CO., LTD.");
        sparseArray.put(11392, "motomobile AG");
        sparseArray.put(11393, "Indie Semiconductor");
        sparseArray.put(11397, "Audientes");
        sparseArray.put(11403, "Huizhou Dehong Technology Co., Ltd.");
        sparseArray.put(11404, "PowerCenter Technology Limited");
        sparseArray.put(11405, "Mizco International, Inc.");
        sparseArray.put(11408, "I. AM. PLUS, LLC");
        sparseArray.put(11409, "Corigine, Inc.");
        sparseArray.put(11410, "Ningbo Yinzhou Shengke Electronics Co., Ltd.");
        sparseArray.put(11417, "Prusa Research s.r.o.");
        sparseArray.put(11423, "e-Smart Systems Pvt. Ltd.");
        sparseArray.put(11424, "Leagtech Jiangxi Electronic Co., Ltd.");
        sparseArray.put(11425, "Dongguan Yujia Electronics Technology Co., Ltd.");
        sparseArray.put(11426, "GuangZhou MingPing Electronics Technology");
        sparseArray.put(11427, "DJI Technology Co., Ltd.");
        sparseArray.put(11428, "Shenzhen Alex Technology Co., Ltd.");
        sparseArray.put(11433, "JITS TECHNOLOGY CO., LIMITED");
        sparseArray.put(11434, "LIVV Brand llc");
        sparseArray.put(11444, "Ava Enterprises, Inc. dba: Boss Audio Systems");
        sparseArray.put(11448, "Shenzhen Sydixon Electronic Technology Co., Ltd.");
        sparseArray.put(11449, "On-Bright Electronics (Shanghai) Co., Ltd.");
        sparseArray.put(11450, "Dongguan Puxu Industrial Co., Ltd.");
        sparseArray.put(11451, "Shenzhen Soling Indusrtial Co., Ltd.");
        sparseArray.put(11453, "EGGCYTE, INC.");
        sparseArray.put(11455, "Donggguan Yuhua Electronic Co., Ltd.");
        sparseArray.put(11456, "Hangzhou Zero Zero Technology Co., Ltd.");
        sparseArray.put(11462, "Prodigy Technovations Pvt Ltd");
        sparseArray.put(11463, "EmergiTech, Inc");
        sparseArray.put(11464, "Hewlett Packard Enterprise");
        sparseArray.put(11465, "Monolithic Power Systems Inc.");
        sparseArray.put(11467, "USB Memory Direct");
        sparseArray.put(11468, "Silicon Mitus Inc.");
        sparseArray.put(11472, "Technics Global Electronics & JCE Co., Ltd.");
        sparseArray.put(11478, "Immersive Media");
        sparseArray.put(11479, "Cosemi Technologies Inc.");
        sparseArray.put(11481, "Cambrionix Ltd");
        sparseArray.put(11482, "CXUN Co. Ltd.");
        sparseArray.put(11483, "China Tsp Inc");
        sparseArray.put(11490, "Yanfeng Visteon (Chongqing) Automotive Electronics Co");
        sparseArray.put(11491, "Alcorlink Corp.");
        sparseArray.put(11492, "ISBC Ltd.");
        sparseArray.put(11493, "InX8 Inc dba: AKiTiO");
        sparseArray.put(11494, "SDAN Tecchnology Co., Ltd.");
        sparseArray.put(11495, "Lemobile Information Technology (Beijing) Co., Ltd.");
        sparseArray.put(11496, "GongGuan HWX Electronic Technology Co., Ltd.");
        sparseArray.put(11497, "Suzhu Jingshi Electronic Technology Co., Ltd.");
        sparseArray.put(11498, "Zhong Shan City Richsound Electronic Industrial Ltd.");
        sparseArray.put(11499, "Dongguang Kangbang Electronics Co., Ltd.");
        sparseArray.put(1151, "Plantronics, Inc.");
        sparseArray.put(1154, "Kyocera Corporation");
        sparseArray.put(1155, "STMicroelectronics");
        sparseArray.put(1161, "Foxconn / Hon Hai");
        sparseArray.put(1165, "ITE Tech Inc.");
        sparseArray.put(1177, "Yamaha Corporation");
        sparseArray.put(1188, "Hitachi, Ltd.");
        sparseArray.put(1191, "Visioneer");
        sparseArray.put(1193, "Canon Inc.");
        sparseArray.put(1200, "Nikon Corporation");
        sparseArray.put(1201, "Pan International");
        sparseArray.put(1204, "Cypress Semiconductor");
        sparseArray.put(1205, "ROHM Co., Ltd.");
        sparseArray.put(1207, "Compal Electronics, Inc.");
        sparseArray.put(1208, "Seiko Epson Corp.");
        sparseArray.put(1211, "I-O Data Device, Inc.");
        sparseArray.put(1221, "Fujitsu Ltd.");
        sparseArray.put(1227, "FUJIFILM Corporation");
        sparseArray.put(1238, "Mentor Graphics");
        sparseArray.put(1240, "Microchip Technology Inc.");
        sparseArray.put(1241, "Holtek Semiconductor, Inc.");
        sparseArray.put(1242, "Panasonic Corporation");
        sparseArray.put(1245, "Sharp Corporation");
        sparseArray.put(1250, "Exar Corporation");
        sparseArray.put(1254, "Identiv, Inc.");
        sparseArray.put(1256, "Samsung Electronics Co., Ltd.");
        sparseArray.put(1260, "Tokyo Electron Device Limited");
        sparseArray.put(1266, "Chicony Electronics Co., Ltd.");
        sparseArray.put(1271, "Newnex Technology Corp.");
        sparseArray.put(1273, "Brother Industries, Ltd.");
        sparseArray.put(1276, "SUNPLUS TECHNOLOGY CO., LTD.");
        sparseArray.put(1278, "PFU Limited");
        sparseArray.put(1281, "Fujikura/DDK");
        sparseArray.put(1282, "Acer, Inc.");
        sparseArray.put(1287, "Hosiden Corporation");
        sparseArray.put(1293, "Belkin International, Inc.");
        sparseArray.put(1300, "FCI Electronics");
        sparseArray.put(1302, "Longwell Electronics/Longwell Company");
        sparseArray.put(1305, "Star Micronics Co., LTD");
        sparseArray.put(1309, "American Power Conversion");
        sparseArray.put(1314, "ACON, Advanced-Connectek, Inc.");
        sparseArray.put(1343, "Synopsys, Inc.");
        sparseArray.put(1356, "Sony Corporation");
        sparseArray.put(1360, "Fuji Xerox Co., Ltd.");
        sparseArray.put(1367, "ATEN International Co. Ltd.");
        sparseArray.put(1369, "Cadence Design Systems, Inc.");
        sparseArray.put(1386, "WACOM Co., Ltd.");
        sparseArray.put(1389, "EIZO Corporation");
        sparseArray.put(1390, "Elecom Co., Ltd.");
        sparseArray.put(1394, "Conexant Systems, Inc.");
        sparseArray.put(1398, "BAFO/Quality Computer Accessories");
        sparseArray.put(1403, "Y-E Data, Inc.");
        sparseArray.put(1404, "AVM GmbH");
        sparseArray.put(1410, "Roland Corporation");
        sparseArray.put(1412, "RATOC Systems, Inc.");
        sparseArray.put(1419, "Infineon Technologies");
        sparseArray.put(1423, "Alcor Micro, Corp.");
        sparseArray.put(1424, "OMRON Corporation");
        sparseArray.put(1447, "Bose Corporation");
        sparseArray.put(1449, "OmniVision Technologies, Inc.");
        sparseArray.put(1452, "Apple");
        sparseArray.put(1453, "Y.C. Cable U.S.A., Inc");
        sparseArray.put(14627, "National Instruments");
        sparseArray.put(1470, "Tyco Electronics Corp., a TE Connectivity Ltd. company");
        sparseArray.put(1473, "MegaChips Corporation");
        sparseArray.put(1478, "Qualcomm, Inc");
        sparseArray.put(1480, "Foxlink/Cheng Uei Precision Industry Co., Ltd.");
        sparseArray.put(1482, "Ricoh Company Ltd.");
        sparseArray.put(1498, "Microtek International Inc.");
        sparseArray.put(1504, "Symbol Technologies");
        sparseArray.put(1507, "Genesys Logic, Inc.");
        sparseArray.put(1509, "Fuji Electric Co., Ltd.");
        sparseArray.put(1525, "Unixtar Technology Inc.");
        sparseArray.put(1529, "Datalogic ADC");
        sparseArray.put(1535, "LeCroy Corporation");
        sparseArray.put(1539, "Novatek Microelectronics Corp.");
        sparseArray.put(1545, "SMK Manufacturing Inc.");
        sparseArray.put(1551, "Joinsoon Electronics Mfg. Co., Ltd.");
        sparseArray.put(1555, "TransAct Technologies Incorporated");
        sparseArray.put(1561, "Seiko Instruments Inc.");
        sparseArray.put(1582, "JPC/MAIN SUPER Inc.");
        sparseArray.put(1583, "Sin Sheng Terminal & Machine Inc.");
        sparseArray.put(1593, "Chrontel, Inc.");
        sparseArray.put(1611, "Analog Devices, Inc. Development Tools");
        sparseArray.put(1612, "Ji-Haw Industrial Co., Ltd");
        sparseArray.put(1614, "Suyin Corporation");
        sparseArray.put(1621, "Space Shuttle Hi-Tech Co.,Ltd.");
        sparseArray.put(1622, "Glory Mark Electronic Ltd.");
        sparseArray.put(1623, "Tekcon Electronics Corp.");
        sparseArray.put(1624, "Sigma Designs, Inc.");
        sparseArray.put(1631, "Good Way Technology Co., Ltd. & GWC technology Inc");
        sparseArray.put(1632, "TSAY-E (BVI) International Inc.");
        sparseArray.put(1633, "Hamamatsu Photonics K.K.");
        sparseArray.put(1642, "Total Technologies, Ltd.");
        sparseArray.put(1659, "Prolific Technology, Inc.");
        sparseArray.put(16700, "Dell Inc.");
        sparseArray.put(1680, "Golden Bridge Electech Inc.");
        sparseArray.put(1689, "Tektronix, Inc.");
        sparseArray.put(1690, "Askey Computer Corporation");
        sparseArray.put(1709, "Greatland Electronics Taiwan Ltd.");
        sparseArray.put(1710, "Eurofins Digital Testing Belgium");
        sparseArray.put(1720, "Pixela Corporation");
        sparseArray.put(1724, "Oki Data Corporation");
        sparseArray.put(1727, "Leoco Corporation");
        sparseArray.put(1732, "Bizlink Technology, Inc.");
        sparseArray.put(1736, "SIIG, Inc.");
        sparseArray.put(1747, "Mitsubishi Electric Corporation");
        sparseArray.put(1758, "Heisei Technology Co., Ltd.");
        sparseArray.put(1802, "Oki Electric Industry Co., Ltd.");
        sparseArray.put(1805, "Comoss Electronic Co., Ltd.");
        sparseArray.put(1809, "Magic Control Technology Corp.");
        sparseArray.put(1816, "Imation Corp.");
        sparseArray.put(1838, "Sunix Co., Ltd.");
        sparseArray.put(1846, "Lorom Industrial Co., Ltd.");
        sparseArray.put(1848, "Mad Catz, Inc.");
        sparseArray.put(1899, "HID Global GmbH");
        sparseArray.put(1901, "Denso Corporation");
        sparseArray.put(1913, "Fairchild Semiconductor");
        sparseArray.put(1921, "SanDisk Corporation");
        sparseArray.put(1937, "Copartner Technology Corporation");
        sparseArray.put(1954, "National Technical Systems");
        sparseArray.put(1971, "Plustek, Inc.");
        sparseArray.put(1972, "OLYMPUS CORPORATION");
        sparseArray.put(1975, "TIME Interconnect Ltd.");
        sparseArray.put(1994, "AVerMedia Technologies, Inc.");
        sparseArray.put(1999, "Casio Computer Co., Ltd.");
        sparseArray.put(2015, "David Electronics Company, Ltd.");
        sparseArray.put(2039, "Century Corporation");
        sparseArray.put(2058, "Evermuch Technology Co., Ltd.");
        sparseArray.put(2101, "Action Star Enterprise Co., Ltd.");
        sparseArray.put(2112, "Argosy Research Inc.");
        sparseArray.put(2122, "Wipro Limited");
        sparseArray.put(2159, "MEC IMEX INC/HPT");
        sparseArray.put(2205, "Icron Technologies Corporation");
        sparseArray.put(2247, "TAI TWUN ENTERPRISE CO., LTD.");
        sparseArray.put(2276, "Pioneer Corporation");
        sparseArray.put(2278, "Gemalto SA");
        sparseArray.put(2310, "FARADAY Technology Corp.");
        sparseArray.put(2313, "Audio-Technica Corp.");
        sparseArray.put(2316, "Silicon Motion, Inc. - Taiwan");
        sparseArray.put(2334, "Garmin International");
        sparseArray.put(2352, "Toshiba Corporation");
        sparseArray.put(2362, "Pixart Imaging, Inc.");
        sparseArray.put(2363, "Plextor LLC");
        sparseArray.put(2366, "J.S.T. Mfg. Co., Ltd.");
        sparseArray.put(2385, "Kingston Technology Company");
        sparseArray.put(2389, "NVIDIA");
        sparseArray.put(2395, "Medialogic Corporation");
        sparseArray.put(2397, "Polycom, Inc.");
        sparseArray.put(2468, "Contech Research, Inc.");
        sparseArray.put(2472, "Lin Shiung Enterprise Co., Ltd.");
        sparseArray.put(2475, "Japan Cash Machine Co., Ltd.");
        sparseArray.put(2498, "NISCA Corporation");
        sparseArray.put(2511, "Electronics Testing Center, Taiwan");
        sparseArray.put(2522, "A-FOUR TECH CO., LTD.");
        sparseArray.put(2555, "Altera");
        sparseArray.put(2578, "Cambridge Silicon Radio Ltd.");
        sparseArray.put(2583, "HOYA Corporation");
        sparseArray.put(2631, "Hirose Electric Co., Ltd.");
        sparseArray.put(2636, "COMPUTEX Co., Ltd.");
        sparseArray.put(2640, "Mimaki Engineering Co., Ltd.");
        sparseArray.put(2652, "Broadcom Corp.");
        sparseArray.put(2667, "Green House Co., Ltd.");
        sparseArray.put(2702, "Japan Aviation Electronics Industry Ltd. (JAE)");
        sparseArray.put(2727, "Wincor Nixdorf GmbH & Co KG");
        sparseArray.put(2733, "Rohde & Schwarz GmbH & Co. KG");
        sparseArray.put(2787, "Allion Labs, Inc.");
        sparseArray.put(2821, "ASUSTek Computer Inc.");
        sparseArray.put(2849, "Yokogawa Electric Corporation");
        sparseArray.put(2851, "Pan-Asia Electronics Co., Ltd.");
        sparseArray.put(2894, "Musical Electronics Ltd.");
        sparseArray.put(2907, "Anritsu Corporation");
        sparseArray.put(2922, "Maxim Integrated Products");
        sparseArray.put(2965, "ASIX Electronics Corporation");
        sparseArray.put(2967, "O2Micro, Inc.");
        sparseArray.put(3010, "Seagate Technology LLC");
        sparseArray.put(3034, "Realtek Semiconductor Corp.");
        sparseArray.put(3035, "Ericsson AB");
        sparseArray.put(3044, "Elka International Ltd.");
        sparseArray.put(3056, "Pace Micro Technology PLC");
        sparseArray.put(3108, "Taiyo Yuden Co., Ltd.");
        sparseArray.put(3129, "Aeroflex");
        sparseArray.put(3132, "Radius Co., Ltd.");
        sparseArray.put(3141, "Sonix Technology Co., Ltd.");
        sparseArray.put(3158, "Billion Bright (HK) Corporation Limited");
        sparseArray.put(3161, "Dong Guan Shinko Wire Co., Ltd.");
        sparseArray.put(3170, "Chant Sincere Co., Ltd");
        sparseArray.put(3190, "Solid State System Co., Ltd.");
        sparseArray.put(3209, "Honda Tsushin Kogyo Co., Ltd");
        sparseArray.put(3245, "Motorola Solutions");
        sparseArray.put(3255, "Singatron Enterprise Co. Ltd.");
        sparseArray.put(3268, "emsys Embedded Systems GmbH");
        sparseArray.put(32902, "Intel Corporation");
        sparseArray.put(3294, "Z-Com INC.");
        sparseArray.put(3313, "e-CONN ELECTRONIC CO., LTD.");
        sparseArray.put(3314, "ENE Technology Inc.");
        sparseArray.put(3351, "NALTEC, Inc.");
        sparseArray.put(3402, "NF Corporation");
        sparseArray.put(3403, "Grape Systems Inc.");
        sparseArray.put(3409, "Volex (Asia) Pte Ltd");
        sparseArray.put(3425, "MEILU ELECTRONICS (SHENZHEN) CO., LTD.");
        sparseArray.put(3441, "Hirakawa Hewtech Corp.");
        sparseArray.put(3452, "Taiwan Line Tek Electronic Co., Ltd.");
        sparseArray.put(3463, "Dolby Laboratories Inc.");
        sparseArray.put(3468, "C-MEDIA ELECTRONICS INC.");
        sparseArray.put(3472, "Sure-Fire Electrical Corporation");
        sparseArray.put(3495, "IOGEAR, Inc.");
        sparseArray.put(3504, "Micro-Star International Co., Ltd.");
        sparseArray.put(3537, "Contek Electronics Co., Ltd.");
        sparseArray.put(3540, "Custom Engineering SPA");
        sparseArray.put(3641, "Smart Modular Technologies, Inc.");
        sparseArray.put(3658, "Shenzhen Bao Hing Electric Wire & Cable Mfr. Co.");
        sparseArray.put(3673, "Bourns, Inc.");
        sparseArray.put(3690, "Megawin Technology Co., Ltd.");
        sparseArray.put(3698, "Hsi-Chin Electronics Co., Ltd.");
        sparseArray.put(3714, "Ching Tai Electric Wire & Cable Co., Ltd.");
        sparseArray.put(3724, "Well Force Electronic Co., Ltd");
        sparseArray.put(3725, "MediaTek Inc.");
        sparseArray.put(3728, "CRU");
        sparseArray.put(3744, "Ours Technology Inc.");
        sparseArray.put(3762, "Y-S ELECTRONIC CO., LTD.");
        sparseArray.put(3778, "Sweetray Industrial Ltd.");
        sparseArray.put(3779, "Axell Corporation");
        sparseArray.put(3782, "InnoVISION Multimedia Limited");
        sparseArray.put(3790, "TaiSol Electronics Co., Ltd.");
        sparseArray.put(3812, "Sunrich Technology (H.K.) Ltd.");
        sparseArray.put(3868, "Funai Electric Co., Ltd.");
        sparseArray.put(3873, "IOI Technology Corporation");
        sparseArray.put(3890, "YFC-BonEagle Electric Co., Ltd.");
        sparseArray.put(3896, "Nien-Yi Industrial Corp.");
        sparseArray.put(3916, "WORLDWIDE CABLE OPTO CORP.");
        sparseArray.put(3923, "Taiyo Cable (Dongguan) Co. Ltd.");
        sparseArray.put(3924, "Kawai Musical Instruments Mfg. Co., Ltd.");
        sparseArray.put(3936, "GuangZhou Chief Tech Electronic Technology Co. Ltd.");
        sparseArray.put(3944, "UQUEST, LTD.");
        sparseArray.put(3991, "CviLux Corporation");
        sparseArray.put(4003, "Chief Land Electronic Co., Ltd.");
        sparseArray.put(4046, "Sony Mobile Communications");
        sparseArray.put(4087, "CHI SHING COMPUTER ACCESSORIES CO., LTD.");
        sparseArray.put(4096, "Speed Tech Corp.");
        sparseArray.put(4100, "LG Electronics Inc.");
        sparseArray.put(4101, "Apacer Technology Inc.");
        sparseArray.put(4134, "Newly Corporation");
        sparseArray.put(4168, "Targus Group International");
        sparseArray.put(4172, "AMCO TEC International Inc.");
        sparseArray.put(4183, "ON Semiconductor");
        sparseArray.put(4184, "Western Digital Technologies, Inc.");
        sparseArray.put(4227, "CANON ELECTRONICS INC.");
        sparseArray.put(4235, "Grand-tek Technology Co., Ltd.");
        sparseArray.put(4236, "Robert Bosch GmbH");
        sparseArray.put(4238, "Lotes Co., Ltd.");
        sparseArray.put(4266, "Cables To Go");
        sparseArray.put(4267, "Universal Global Scientific Industrial Co., Ltd.");
        sparseArray.put(4292, "Silicon Laboratories, Inc.");
        sparseArray.put(4301, "Kycon Inc.");
        sparseArray.put(4362, "Moxa Inc.");
        sparseArray.put(4370, "Golden Bright (Sichuan) Electronic Technology Co Ltd");
        sparseArray.put(4382, "VSO ELECTRONICS CO., LTD.");
        sparseArray.put(4398, "Master Hill Electric Wire and Cable Co., Ltd.");
        sparseArray.put(4477, "Santa Electronic Inc.");
        sparseArray.put(4505, "Sierra Wireless Inc.");
        sparseArray.put(4522, "GlobalMedia Group, LLC");
        sparseArray.put(4528, "ATECH FLASH TECHNOLOGY");
        sparseArray.put(4643, "SKYCABLE ENTERPRISE CO., LTD.");
        sparseArray.put(4703, "ADATA Technology Co., Ltd.");
        sparseArray.put(4716, "Aristocrat Technologies");
        sparseArray.put(4717, "Bel Stewart");
        sparseArray.put(4742, "MARVELL SEMICONDUCTOR, INC.");
        sparseArray.put(4756, "RISO KAGAKU CORP.");
        sparseArray.put(4792, "Zhejiang Xinya Electronic Technology Co., Ltd.");
        sparseArray.put(4817, "Huawei Technologies Co., Ltd.");
        sparseArray.put(4823, "Better Holdings (HK) Limited");
        sparseArray.put(4907, "Konica Minolta, Inc.");
        sparseArray.put(4925, "Jasco Products Company");
        sparseArray.put(4989, "Pericom Semiconductor Corp.");
        sparseArray.put(5008, "TomTom International B.V.");
        sparseArray.put(5075, "AzureWave Technologies, Inc.");
        sparseArray.put(5117, "Initio Corporation");
        sparseArray.put(5118, "Phison Electronics Corp.");
        sparseArray.put(5134, "Telechips, Inc.");
        sparseArray.put(5145, "ABILITY ENTERPRISE CO., LTD.");
        sparseArray.put(5148, "Leviton Manufacturing");
        sparseArray.put(5271, "Panstrong Company Ltd.");
        sparseArray.put(5293, "CTK Corporation");
        sparseArray.put(5296, "StarTech.com Ltd.");
        sparseArray.put(5376, "Ellisys");
        sparseArray.put(5404, "VeriSilicon Holdings Co., Ltd.");
        sparseArray.put(5421, "JMicron Technology Corp.");
        sparseArray.put(5422, "HLDS (Hitachi-LG Data Storage, Inc.)");
        sparseArray.put(5440, "Phihong Technology Co., Ltd.");
        sparseArray.put(5451, "PNY Technologies Inc.");
        sparseArray.put(5453, "Rapid Conn, Connect County Holdings Bhd");
        sparseArray.put(5454, "D & M Holdings, Inc.");
        sparseArray.put(5480, "Sunf Pu Technology Co., Ltd");
        sparseArray.put(5488, "ALLTOP TECHNOLOGY CO., LTD.");
        sparseArray.put(5510, "Palconn Technology Co., Ltd.");
        sparseArray.put(5528, "Kunshan Guoji Electronics Co., Ltd.");
        sparseArray.put(5546, "DongGuan Ya Lian Electronics Co., Ltd.");
        sparseArray.put(5645, "Samtec");
        sparseArray.put(5694, "HongLin Electronics Co., Ltd.");
        sparseArray.put(5753, "Total Phase");
        sparseArray.put(5766, "ZOOM Corporation");
        sparseArray.put(5836, "silex technology, Inc.");
        sparseArray.put(5946, "F. Hoffmann-La Roche AG");
        sparseArray.put(5960, "MQP Electronics Ltd.");
        sparseArray.put(5964, "ASMedia Technology Inc.");
        sparseArray.put(5998, "UD electronic corp.");
        sparseArray.put(AuthCode.StatusCode.WAITING_CONNECT, "Shenzhen Alex Connector Co., Ltd.");
        sparseArray.put(AuthCode.StatusCode.AUTH_INFO_NOT_EXIST, "System Level Solutions, Inc.");
        sparseArray.put(6018, "Spreadtrum Hong Kong Limited");
        sparseArray.put(6024, "ShenZhen Litkconn Technology Co., Ltd.");
        sparseArray.put(6053, "Advanced Connection Technology Inc.");
        sparseArray.put(6095, "Hip Hing Cable & Plug Mfy. Ltd.");
        sparseArray.put(6121, "DisplayLink (UK) Ltd.");
        sparseArray.put(6127, "Lenovo");
        sparseArray.put(6133, "K.K. Rocky");
        sparseArray.put(6160, "Wanshih Electronic Co., Ltd.");
        sparseArray.put(6185, "Dongguan YuQiu Electronics Co., Ltd.");
        sparseArray.put(6193, "Gwo Jinn Industries Co., Ltd.");
        sparseArray.put(6297, "Linkiss Co., Ltd.");
        sparseArray.put(6353, "Google Inc.");
        sparseArray.put(6394, "Kuang Ying Computer Equipment Co., Ltd.");
        sparseArray.put(6421, "Nordic Semiconductor ASA");
        sparseArray.put(6448, "Shenzhen Xianhe Technology Co., Ltd.");
        sparseArray.put(6449, "Ningbo Broad Telecommunication Co., Ltd.");
        sparseArray.put(6470, "Irisguard UK Ltd");
        sparseArray.put(6473, "Lab126");
        sparseArray.put(6481, "Hyperstone GmbH");
        sparseArray.put(6487, "BIOS Corporation");
        sparseArray.put(6626, "Solomon Systech Limited");
        sparseArray.put(6639, "Pak Heng Technology (Shenzhen) Co., Ltd.");
        sparseArray.put(6655, "Best Buy China Ltd.");
        sparseArray.put(6666, "USB-IF non-workshop");
        sparseArray.put(6709, "Artesyn Technologies Inc.");
        sparseArray.put(6720, "TERMINUS TECHNOLOGY INC.");
        sparseArray.put(6766, "Global Unichip Corp.");
        sparseArray.put(6786, "Proconn Technology Co., Ltd.");
        sparseArray.put(6794, "Simula Technology Inc.");
        sparseArray.put(6795, "SGS Taiwan Ltd.");
        sparseArray.put(6830, "Johnson Component & Equipments Co., Ltd.");
        sparseArray.put(6834, "Allied Vision Technologies GmbH");
        sparseArray.put(6859, "Salcomp Plc");
        sparseArray.put(6865, "Desan Wire Co., Ltd.");
        sparseArray.put(6944, "MStar Semiconductor, Inc.");
        sparseArray.put(6984, "Plastron Precision Co., Ltd.");
        sparseArray.put(7013, "The Hong Kong Standards and Testing Centre Ltd.");
        sparseArray.put(7048, "ShenMing Electron (Dong Guan) Co., Ltd.");
        sparseArray.put(7086, "Vuzix Corporation");
        sparseArray.put(7108, "Ford Motor Co.");
        sparseArray.put(7118, "Contac Cable Industrial Limited");
        sparseArray.put(7119, "Sunplus Innovation Technology Inc.");
        sparseArray.put(7120, "Hangzhou Riyue Electronics Co., Ltd.");
        sparseArray.put(7158, "Orient Semiconductor Electronics, Ltd.");
        sparseArray.put(7207, "SHENZHEN DNS INDUSTRIES CO., LTD.");
        sparseArray.put(7217, "LS Mtron Ltd.");
        sparseArray.put(7229, "NONIN MEDICAL INC.");
        sparseArray.put(7275, "Philips & Lite-ON Digital Solutions Corporation");
        sparseArray.put(7310, "ASTRON INTERNATIONAL CORP.");
        sparseArray.put(7320, "ALPINE ELECTRONICS, INC.");
        sparseArray.put(7347, "Aces Electronics Co., Ltd.");
        sparseArray.put(7348, "OPEX CORPORATION");
        sparseArray.put(7390, "Telecommunications Technology Association (TTA)");
        sparseArray.put(7434, "Visteon Corporation");
        sparseArray.put(7465, "Horng Tong Enterprise Co., Ltd.");
        sparseArray.put(7501, "Pegatron Corporation");
        sparseArray.put(7516, "Fresco Logic Inc.");
        sparseArray.put(7529, "Walta Electronic Co., Ltd.");
        sparseArray.put(7543, "Yueqing Changling Electronic Instrument Corp., Ltd.");
        sparseArray.put(7584, "Parade Technologies, Inc.");
        sparseArray.put(7647, "L&T Technology Services");
        sparseArray.put(7649, "Actions Microelectronics Co., Ltd.");
        sparseArray.put(7666, "China Telecommunication Technology Labs - Terminals");
        sparseArray.put(7668, "SHEN ZHEN FORMAN PRECISION INDUSTRY CO., LTD.");
        sparseArray.put(7682, "GLOBEMASTER TECHNOLOGIES CO., LTD.");
        sparseArray.put(7696, "Point Grey Research Inc.");
        sparseArray.put(7751, "HUNG TA H.T.ENTERPRISE CO., LTD.");
        sparseArray.put(7758, "Etron Technology, Inc.");
        sparseArray.put(7795, "COMLINK ELECTRONICS CO., LTD.");
        sparseArray.put(7818, "HIBEST Electronic (DongGuan) Co., Ltd.");
        sparseArray.put(7825, "Other World Computing");
        sparseArray.put(7863, "WIN WIN PRECISION INDUSTRIAL CO., LTD.");
        sparseArray.put(7879, "Gefen Inc.");
        sparseArray.put(7881, "MOSER BAER INDIA LIMITED");
        sparseArray.put(7898, "AIRTIES WIRELESS NETWORKS");
        sparseArray.put(7956, "Astoria Networks GmbH");
        sparseArray.put(7969, "Scosche Industries");
        sparseArray.put(7976, "Cal-Comp Electronics & Communications");
        sparseArray.put(7977, "Analogix Semiconductor, Inc.");
        sparseArray.put(7989, "Amphenol ShouhMin Industry (ShenZhen) Co., Ltd");
        sparseArray.put(7996, "Chang Yang Electronics Company Ltd.");
        sparseArray.put(8073, "Dongguan Goldconn Electronics Co., Ltd.");
        sparseArray.put(8074, "Morning Star Industrial Co., Ltd.");
        sparseArray.put(8117, "Unify Software and Solutions GmbH & Co. KG");
        sparseArray.put(8137, "NXP Semiconductors");
        sparseArray.put(8181, "Changzhou Wujin BEST Electronic Cables Co., Ltd.");
        sparseArray.put(8205, "Belkin Electronic (Changzhou) Co., Ltd.");
        sparseArray.put(8220, "Freeport Resources Enterprises Corp.");
        sparseArray.put(8222, "Qingdao Haier Telecom Co., Ltd.");
        sparseArray.put(8284, "Shenzhen Tronixin Electronics Co., Ltd.");
        sparseArray.put(8294, "Unicorn Electronics Components Co., Ltd.");
        sparseArray.put(8334, "Luxshare-ICT");
        sparseArray.put(8341, "CE LINK LIMITED");
        sparseArray.put(8342, "Microconn Electronic Co., Ltd.");
        sparseArray.put(8367, "Shenzhen CARVE Electronics Co., Ltd.");
        sparseArray.put(8382, "BURY GmbH & Co. KG");
        sparseArray.put(8384, "FENGHUA KINGSUN CO., LTD.");
        sparseArray.put(8386, "Sumitomo Electric Ind., Ltd., Optical Comm. R&D Lab");
        sparseArray.put(8439, "XIMEA s.r.o.");
        sparseArray.put(8457, "VIA Labs, Inc.");
        sparseArray.put(8492, "Shenzhen Linoya Electronic Co., Ltd.");
        sparseArray.put(8494, "Amphenol AssembleTech (Xiamen) Co., Ltd.");
        sparseArray.put(8524, "Y Soft Corporation");
        sparseArray.put(8550, "JVC KENWOOD Corporation");
        sparseArray.put(8564, "Transcend Information, Inc.");
        sparseArray.put(8566, "TMC/Allion Test Labs");
        sparseArray.put(8613, "Genesis Technology USA, Inc.");
        sparseArray.put(8627, "Dongguan Teconn Electronics Technology Co., Ltd.");
        sparseArray.put(8644, "Netcom Technology (HK) Limited");
        sparseArray.put(8659, "Compupack Technology Co., Ltd.");
        sparseArray.put(8667, "G-Max Technology Co., Ltd.");
        sparseArray.put(8679, "Sagemcom Broadband SAS");
        sparseArray.put(8695, "Wuerth-Elektronik eiSos GmbH & Co. KG");
        sparseArray.put(8707, "Shin Shin Co., Ltd.");
        sparseArray.put(8709, "3eYamaichi Electronics Co., Ltd.");
        sparseArray.put(8710, "Wiretek International Investment Ltd.");
        sparseArray.put(8711, "Fuzhou Rockchip Electronics Co., Ltd.");
        sparseArray.put(8752, "Plugable Technologies");
        sparseArray.put(8756, "T-CONN PRECISION CORPORATION");
        sparseArray.put(8831, "Granite River Labs");
        sparseArray.put(8842, "Hotron Precision Electronic Ind. Corp.");
        sparseArray.put(8875, "Trigence Semiconductor, Inc.");
        sparseArray.put(8888, "Motorola Mobility Inc.");
        sparseArray.put(8904, "Karming Electronic (Shenzhen) Co., Ltd.");
        sparseArray.put(8981, "Avery Design Systems, Inc.");
        sparseArray.put(8993, "iKingdom Corp. (d.b.a. iConnectivity)");
        sparseArray.put(9051, "KangXiang Electronic Co., Ltd.");
        sparseArray.put(9068, "ZheJiang Chunsheng Electronics Co., Ltd.");
        sparseArray.put(9130, "DOK (HK) Trading Limited");
        sparseArray.put(9132, "Marunix Electron Limited");
        sparseArray.put(9165, "Avconn Precise Connector Co., Ltd.");
        sparseArray.put(9184, "BitifEye Digital Test Solutions GmbH");
        sparseArray.put(9205, "Speed Conn Co., Ltd.");
        sparseArray.put(9222, "INSIDE Secure");
        sparseArray.put(9292, "Minebea Co., Ltd.");
        sparseArray.put(9299, "BAANTO");
        sparseArray.put(9338, "Suzhou Jutze Technologies Co., Ltd");
        sparseArray.put(9355, "DONGGUAN SYNCONN PRECISION INDUSTRY CO. LTD.");
        sparseArray.put(9382, "Shenzhen Pangngai Industrial Co., Ltd.");
        sparseArray.put(9422, "Shenzhen Deren Electronic Co., Ltd.");
        sparseArray.put(9424, "Smith Micro Software, Inc.");
        sparseArray.put(9453, "ZEN FACTORY GROUP (ASIA) LTD.");
        sparseArray.put(9481, "Chain-In Electronic Co., Ltd.");
        sparseArray.put(9514, "SUZHOU KELI TECHNOLOGY DEVELOPMENT CO., LTD.");
        sparseArray.put(9515, "TOP Exactitude Industry (ShenZhen) Co., Ltd.");
        sparseArray.put(9525, "ShenZhen Hogend Precision Technology Co., Ltd.");
        sparseArray.put(9527, "Norel Systems Ltd.");
        sparseArray.put(9556, "ASSA ABLOY AB");
        sparseArray.put(9575, "DongGuan LongTao Electronic Co., Ltd.");
        sparseArray.put(9577, "DongGuan City MingJi Electronics Co., Ltd.");
        sparseArray.put(9589, "Weida Hi-Tech Co., Ltd.");
        sparseArray.put(9593, "Dongguan Wisechamp Electronic Co., Ltd.");
        sparseArray.put(9613, "Sequans Communications");
        sparseArray.put(9636, "ALGOLTEK, INC.");
        sparseArray.put(9651, "DongGuan Elinke Industrial Co., Ltd.");
        sparseArray.put(9679, "Corning Optical Communications LLC");
        sparseArray.put(9714, "Dongguan Jinyue Electronics Co., Ltd.");
        sparseArray.put(9723, "RICOH IMAGING COMPANY, LTD.");
        sparseArray.put(9742, "DongGuan HYX Industrial Co., Ltd.");
        sparseArray.put(9753, "Advanced Silicon SA");
        sparseArray.put(9756, "EISST Limited");
        sparseArray.put(9771, "YTOP Electronics Technical (Kunshan) Co., Ltd.");
        sparseArray.put(9841, "Innovative Logic");
        sparseArray.put(9842, "GoPro");
        sparseArray.put(9846, "Basler AG");
        sparseArray.put(9851, "Palpilot International Corp.");
        sparseArray.put(9896, "UNIREX CORPORATION");
        sparseArray.put(9917, "Integral Memory Plc.");
        sparseArray.put(9973, "Morning Star Digital Connector Co., Ltd.");
        sparseArray.put(9984, "MITACHI CO., LTD.");
        sparseArray.put(9999, "HGST, a Western Digital Company");
    }

    public static String vendorName(int i) {
        return IDS.get(i);
    }
}
