package com.larksuite.component.openplatform.core.p1114c;

import com.bytedance.ee.lark.infra.foundation.log.AppBrandLogger;
import com.bytedance.ee.lark.infra.foundation.schedulers.Action;
import com.bytedance.ee.lark.infra.foundation.schedulers.Schedulers;
import com.bytedance.ee.larkbrand.LarkExtensionManager;
import com.bytedance.ee.larkbrand.nativeMoudule.rich.LarkApiHideRichTextCtrlPlugin;
import com.bytedance.ee.larkbrand.nativeMoudule.rich.LarkApiShowRichTextCtrlPlugin;
import com.bytedance.ee.webapp.api.LarkApiChangeStatusBarColorPlugin;
import com.bytedance.ee.webapp.api.LarkApiInspectDebugListPlugin;
import com.bytedance.ee.webapp.api.LarkApiRequestAuthCodePlugin;
import com.lark.falcon.engine.CreateWorkerPlugin;
import com.larksuite.component.openplatform.core.plugin.KeyboardPlugin;
import com.larksuite.component.openplatform.core.plugin.OPCallTranslateActivityPlugin;
import com.larksuite.component.openplatform.core.plugin.OPEventReportPlugin;
import com.larksuite.component.openplatform.core.plugin.OPFileInnerPlugin;
import com.larksuite.component.openplatform.core.plugin.OPGadgetLifecyclePlugin;
import com.larksuite.component.openplatform.core.plugin.OPKillGadgetPlugin;
import com.larksuite.component.openplatform.core.plugin.OPLifecyclePlugin;
import com.larksuite.component.openplatform.core.plugin.OPTransferMessagePlugin;
import com.larksuite.component.openplatform.core.plugin.PadDisplayScalePlugin;
import com.larksuite.component.openplatform.core.plugin.applink.C24581b;
import com.larksuite.component.openplatform.core.plugin.applink.OpenSchemaAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.authorization.ApiAuthorizePlugin;
import com.larksuite.component.openplatform.core.plugin.ccm.ApiDocsPickerPlugin;
import com.larksuite.component.openplatform.core.plugin.ccm.OpenDocumentAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiApplyUpdatePlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiCanvasSyncPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiHideShareMenuCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiOpenModalWebViewCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiOperateModalWebViewStateCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiSetMenuButtonVisibilityCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiShowMorePanelCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiShowShareMenuCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiStartPullDownRefreshCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.ApiStopPullDownRefreshCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.C24656b;
import com.larksuite.component.openplatform.core.plugin.container.C24659c;
import com.larksuite.component.openplatform.core.plugin.container.LarkApiDisablePullDownRefreshCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.LarkApiEnablePullDownRefreshCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.LarkApiGetShowModalTipInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.container.OnBackPressPlugin;
import com.larksuite.component.openplatform.core.plugin.container.SetKeyboardValueSyncPlugin;
import com.larksuite.component.openplatform.core.plugin.container.navigation.ApiHideHomeButtonCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.navigation.ApiHideNavigationBarLoadingCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.navigation.ApiSetNavigationBarColorPlugin;
import com.larksuite.component.openplatform.core.plugin.container.navigation.ApiSetNavigationBarTitlePlugin;
import com.larksuite.component.openplatform.core.plugin.container.navigation.ApiShowNavigationBarLoadingCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.AddTabBarItemPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiHideTabBarPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiHideTabBarRedDotPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiRemoveTabBarBadgePlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiSetTabBarItemPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiSetTabBarStylePlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiSetTabbarBadgePlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiShowTabBarPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.ApiShowTabBarRedDotPlugin;
import com.larksuite.component.openplatform.core.plugin.container.tabbar.RemoveTabBarItemPlugin;
import com.larksuite.component.openplatform.core.plugin.device.SetKeepScreenOnPlugin;
import com.larksuite.component.openplatform.core.plugin.device.accelerometer.ApiEnableAccelerometerPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiCloseBluetoothCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiGetBluetoothDevicesCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiGetBluetoothStateCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiGetConnectedBluetoothDevicesCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiOpenBluetoothCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiStartBluetoothDiscoveryCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.api.LarkApiStopBluetoothDiscoveryCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.ibeacon.GetBeaconsPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.ibeacon.StartBeaconDiscoveryPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.ibeacon.StopBeaconDiscoveryPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiConnectBLEDeviceCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiDisconnectBLEDeviceCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiGetBLEDeviceCharacteristicsCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiGetBLEDeviceServicesCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiNotifyBLECharacteristicValueChangeCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiReadBLECharacteristicValueCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiSetBLEMTUCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.bluetooth.le.LarkApiWriteBLECharacteristicValueCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcCloseAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcConnectAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcGetAtqaAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcGetSakAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcMaxTransAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcSetTimeoutAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcStartDiscoveryAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcStopDiscoveryAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.nfc.NfcTransceiveAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.device.step.GetRunStepCountPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.C24876b;
import com.larksuite.component.openplatform.core.plugin.infra.GetSystemInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiAccessCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiCopyFileCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiMkDirCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiReadDirCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiRenameCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiRmDirCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiSaveFileCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiStatCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiUnlinkCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.ApiUnzipCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.C24912m;
import com.larksuite.component.openplatform.core.plugin.infra.file.C24913n;
import com.larksuite.component.openplatform.core.plugin.infra.file.read.ApiReadFileCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.file.write.ApiWriteFileCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.ApiOperateSocketTaskV2Plugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24929b;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24930c;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24932d;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24933e;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24936h;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24938i;
import com.larksuite.component.openplatform.core.plugin.infra.network.C24944m;
import com.larksuite.component.openplatform.core.plugin.infra.network.CreateDownloadFileTaskSyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.CreateSocketTaskSyncV2Plugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.GetNetWorkTypeAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.GetNetworkQualityTypeAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.NetworkQualityChangeAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.network.OperateDownloadFileTaskAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.p1134a.C24874b;
import com.larksuite.component.openplatform.core.plugin.infra.storage.ApiGetFileInfoCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.ApiGetSavedFileInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.ApiGetSavedFileListCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.Base64ToTempFilePathPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.C24966f;
import com.larksuite.component.openplatform.core.plugin.infra.storage.C24968h;
import com.larksuite.component.openplatform.core.plugin.infra.storage.RemoveSavedFilePlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.storage.ClearStoragePlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.storage.GetStorageInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.storage.GetStoragePlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.storage.RemoveStoragePlugin;
import com.larksuite.component.openplatform.core.plugin.infra.storage.storage.SetStoragePlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiConsoleLogOutputPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiErrorLogCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiLogCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiMonitorReportHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiPreloadMiniProgramCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiReportAnalyticsCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiReportJsRuntimeErrorCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiReportTimeLinePointsCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.ApiSystemLogCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.inner.C25008i;
import com.larksuite.component.openplatform.core.plugin.inner.C25011l;
import com.larksuite.component.openplatform.core.plugin.inner.LarkApiGetServerTimePlugin;
import com.larksuite.component.openplatform.core.plugin.inner.LarkApiReportAnalyticsPlugin;
import com.larksuite.component.openplatform.core.plugin.media.ChooseVideoHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.media.CompressImageHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.media.GetImageInfoHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.media.PreviewImageHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.media.SaveImageToPhotosAlbumHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.media.SaveVideoToPhotosAlbumHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.ApiChooseLocationCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.ApiFilePickerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.C25116b;
import com.larksuite.component.openplatform.core.plugin.messenger.CheckWatermarkPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.EnterProfileAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.GetActionMessageInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.HideToastHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.LarkApiChooseContactPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.LarkApiEnterBotPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.LarkApiPromptCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.LarkChatBadgeChangePlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.OpenChatIdPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.OpenDepartmentIdPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.OpenIdPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.ShowActionSheetHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.ShowModalHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.ShowToastHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.appbadge.ReportBadgeHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.appbadge.UpdateBadgeHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.chat.ChooseChatPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.chat.GetChatInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.liveAuthentication.ApiSetAuthInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.liveAuthentication.ApiStartFaceIdentifyPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.liveAuthentication.ApiStartFaceVerifyPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.location.GetLocationAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.location.LarkApiGetLocationStatusPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.location.LarkApiOpenLocationCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.sendmsg.ApiSendMsgCardPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.sendmsg.C25250a;
import com.larksuite.component.openplatform.core.plugin.messenger.sendmsg.GetTriggerContextHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.messenger.share.ShareAppMessagePlugin;
import com.larksuite.component.openplatform.core.plugin.op.ApiGetAppBrandSettingsCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.op.ApiGetAppInfoSyncPlugin;
import com.larksuite.component.openplatform.core.plugin.op.ApiGetExtConfigPlugin;
import com.larksuite.component.openplatform.core.plugin.op.ApiGetHostLaunchQueryPlugin;
import com.larksuite.component.openplatform.core.plugin.op.ApiRemoveRecentAppsCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.op.C25329aa;
import com.larksuite.component.openplatform.core.plugin.op.C25330ab;
import com.larksuite.component.openplatform.core.plugin.op.C25379c;
import com.larksuite.component.openplatform.core.plugin.op.C25381d;
import com.larksuite.component.openplatform.core.plugin.op.C25384f;
import com.larksuite.component.openplatform.core.plugin.op.C25386g;
import com.larksuite.component.openplatform.core.plugin.op.C25429w;
import com.larksuite.component.openplatform.core.plugin.op.CheckSessionAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.op.GetHostLaunchQuerySyncPlugin;
import com.larksuite.component.openplatform.core.plugin.op.GetLaunchOptionsSyncPlugin;
import com.larksuite.component.openplatform.core.plugin.op.GetTimingSettingPlugin;
import com.larksuite.component.openplatform.core.plugin.op.H5ApiGetEnvironmentVariablePlugin;
import com.larksuite.component.openplatform.core.plugin.op.ShowErrorPagePlugin;
import com.larksuite.component.openplatform.core.plugin.op.appscope.ApplyTenantAppScopeAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.op.appscope.GetTenantAppScopesAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.op.inspirecloud.InspireCloudHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.passport.ApiStartPasswordVerifyPlugin;
import com.larksuite.component.openplatform.core.plugin.passport.C25449a;
import com.larksuite.component.openplatform.core.plugin.passport.GetEnvConfigPlugin;
import com.larksuite.component.openplatform.core.plugin.passport.GetKaInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.passport.GetUserInfoAsyncHandlerPlugin;
import com.larksuite.component.openplatform.core.plugin.passport.LarkApiGetDeviceIdCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.passport.LoginAsyncHandler;
import com.larksuite.component.openplatform.core.plugin.passport.LoginAsyncPlugin;
import com.larksuite.component.openplatform.core.plugin.router.C25471a;
import com.larksuite.component.openplatform.core.plugin.router.C25472b;
import com.larksuite.component.openplatform.core.plugin.router.C25474d;
import com.larksuite.component.openplatform.core.plugin.router.ExitMiniProgramPlugin;
import com.larksuite.component.openplatform.core.plugin.security.GetSecurityInfoPlugin;
import com.larksuite.component.openplatform.core.plugin.settings.ApiGetSettingPlugin;
import com.larksuite.component.openplatform.core.plugin.settings.ApiOpenSettingPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.async.ApiCreateAudioInstanceCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.async.ApiDestroyAudioInstanceCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.async.ApiGetAudioStateCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.async.ApiOperateAudioCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.async.ApiSetAudioStatePlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.bg.ApiGetBgAudioContextCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.bg.ApiGetBgAudioStateCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.bg.ApiOperateBgAudioCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.bg.ApiSetBgAudioCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.sync.C25513a;
import com.larksuite.component.openplatform.core.plugin.vc.audio.sync.GetAudioStateSyncCtrlPlugin;
import com.larksuite.component.openplatform.core.plugin.vc.audio.sync.OperateAudioRecorderSyncCtrlPlugin;
import com.larksuite.framework.apiplugin.AbstractC25937e;
import com.tt.miniapp.net.CreateUploadTaskPlugin;
import com.tt.miniapp.net.OperateUploadTaskPlugin;
import com.tt.miniapp.webbridge.aysnc.GetHostInfoPlugin;
import com.tt.miniapp.webbridge.sync.C67323a;
import com.tt.miniapp.webbridge.sync.C67392u;
import com.tt.refer.common.util.C67866g;
import java.util.LinkedList;
import java.util.List;

/* renamed from: com.larksuite.component.openplatform.core.c.a */
public class C24423a {
    /* renamed from: d */
    public static List<AbstractC25937e> m89093d() {
        return new LinkedList();
    }

    /* renamed from: a */
    public static void m89090a() {
        C67866g.m264025a(new Action() {
            /* class com.larksuite.component.openplatform.core.p1114c.C24423a.C244241 */

            @Override // com.bytedance.ee.lark.infra.foundation.schedulers.Action
            public void act() {
                long currentTimeMillis = System.currentTimeMillis();
                C24423a.m89091b();
                C24423a.m89092c();
                C24423a.m89093d();
                AppBrandLogger.m52830i("OPApiPluginManager", "preload cost:" + (System.currentTimeMillis() - currentTimeMillis));
            }
        }, Schedulers.longIO());
    }

    /* renamed from: j */
    private static List<AbstractC25937e> m89099j() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new ApiOperateSocketTaskV2Plugin());
        return linkedList;
    }

    /* renamed from: i */
    private static List<AbstractC25937e> m89098i() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new C24938i());
        linkedList.add(new CreateSocketTaskSyncV2Plugin());
        return linkedList;
    }

    /* renamed from: g */
    private static List<AbstractC25937e> m89096g() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new GetLaunchOptionsSyncPlugin());
        linkedList.add(new C67323a());
        linkedList.add(new C24913n("mkdirSync"));
        linkedList.add(new C24913n("rmdirSync"));
        linkedList.add(new C24913n("statSync"));
        linkedList.add(new C24913n("protocolPathToAbsPath"));
        linkedList.add(new SetKeyboardValueSyncPlugin());
        linkedList.add(new C25384f());
        linkedList.add(new C24874b());
        linkedList.add(new C24944m());
        linkedList.add(new C24966f());
        linkedList.add(new GetHostLaunchQuerySyncPlugin());
        linkedList.add(new C25513a());
        linkedList.add(new ApiReportAnalyticsCtrlPlugin());
        linkedList.add(new LarkApiReportAnalyticsPlugin());
        linkedList.add(new GetAudioStateSyncCtrlPlugin());
        linkedList.add(new OperateAudioRecorderSyncCtrlPlugin());
        linkedList.add(new ApiCanvasSyncPlugin());
        linkedList.add(new ApiGetAppInfoSyncPlugin());
        linkedList.add(new ApiGetExtConfigPlugin());
        linkedList.add(new C24936h());
        linkedList.add(new CreateUploadTaskPlugin());
        linkedList.add(new ApiGetAppBrandSettingsCtrlPlugin());
        linkedList.add(new C24930c());
        return linkedList;
    }

    /* renamed from: h */
    private static List<AbstractC25937e> m89097h() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new LarkChatBadgeChangePlugin());
        linkedList.add(new LarkApiCloseBluetoothCtrlPlugin());
        linkedList.add(new LarkApiGetBluetoothDevicesCtrlPlugin());
        linkedList.add(new LarkApiGetBluetoothStateCtrlPlugin());
        linkedList.add(new LarkApiGetConnectedBluetoothDevicesCtrlPlugin());
        linkedList.add(new LarkApiOpenBluetoothCtrlPlugin());
        linkedList.add(new LarkApiStartBluetoothDiscoveryCtrlPlugin());
        linkedList.add(new LarkApiStopBluetoothDiscoveryCtrlPlugin());
        linkedList.add(new LarkApiConnectBLEDeviceCtrlPlugin());
        linkedList.add(new LarkApiDisconnectBLEDeviceCtrlPlugin());
        linkedList.add(new LarkApiGetBLEDeviceCharacteristicsCtrlPlugin());
        linkedList.add(new LarkApiGetBLEDeviceServicesCtrlPlugin());
        linkedList.add(new LarkApiNotifyBLECharacteristicValueChangeCtrlPlugin());
        linkedList.add(new LarkApiReadBLECharacteristicValueCtrlPlugin());
        linkedList.add(new LarkApiSetBLEMTUCtrlPlugin());
        linkedList.add(new LarkApiWriteBLECharacteristicValueCtrlPlugin());
        linkedList.add(new StartBeaconDiscoveryPlugin());
        linkedList.add(new StopBeaconDiscoveryPlugin());
        linkedList.add(new GetBeaconsPlugin());
        linkedList.add(new ApiSetAuthInfoPlugin());
        linkedList.add(new ApiStartFaceIdentifyPlugin());
        linkedList.add(new ApiStartFaceVerifyPlugin());
        linkedList.add(new LarkApiEnterBotPlugin());
        linkedList.add(new LarkApiGetShowModalTipInfoPlugin());
        if (LarkExtensionManager.getInstance().getExtension().getFeatureGating("openplatform.setting.scope_run_data")) {
            linkedList.add(new GetRunStepCountPlugin());
        }
        linkedList.add(new LarkApiRequestAuthCodePlugin());
        linkedList.add(new LarkApiChangeStatusBarColorPlugin());
        linkedList.add(new LarkApiInspectDebugListPlugin());
        return linkedList;
    }

    /* renamed from: b */
    public static List<AbstractC25937e> m89091b() {
        LinkedList linkedList = new LinkedList();
        linkedList.addAll(m89096g());
        linkedList.addAll(m89098i());
        linkedList.addAll(m89095f());
        linkedList.addAll(m89099j());
        linkedList.addAll(m89097h());
        linkedList.addAll(m89094e());
        linkedList.add(new LoginAsyncHandler());
        linkedList.add(new LoginAsyncPlugin());
        linkedList.add(new GetHostInfoPlugin());
        linkedList.add(new C67392u());
        linkedList.add(new OpenChatIdPlugin());
        linkedList.add(new OpenIdPlugin());
        linkedList.add(new GetChatInfoPlugin());
        linkedList.add(new ChooseChatPlugin());
        linkedList.add(new OpenDepartmentIdPlugin());
        linkedList.add(new OPFileInnerPlugin());
        linkedList.add(new OPEventReportPlugin());
        linkedList.add(new ShareAppMessagePlugin());
        linkedList.add(new GetEnvConfigPlugin());
        linkedList.add(new GetKaInfoPlugin());
        linkedList.add(new ShowToastHandlerPlugin());
        linkedList.add(new HideToastHandlerPlugin());
        linkedList.add(new ShowActionSheetHandlerPlugin());
        linkedList.add(new ShowModalHandlerPlugin());
        linkedList.add(new LarkApiPromptCtrlPlugin());
        linkedList.add(new LarkApiGetDeviceIdCtrlPlugin());
        linkedList.add(new ApiAccessCtrlPlugin());
        linkedList.add(new ApiCopyFileCtrlPlugin());
        linkedList.add(new ApiRenameCtrlPlugin());
        linkedList.add(new ApiReadDirCtrlPlugin());
        linkedList.add(new ApiSaveFileCtrlPlugin());
        linkedList.add(new ApiReadFileCtrlPlugin());
        linkedList.add(new ApiWriteFileCtrlPlugin());
        linkedList.add(new LarkApiShowRichTextCtrlPlugin());
        linkedList.add(new LarkApiHideRichTextCtrlPlugin());
        linkedList.add(new ApiUnzipCtrlPlugin());
        linkedList.add(new ApiUnlinkCtrlPlugin());
        linkedList.add(new ApiGetSavedFileListCtrlPlugin());
        linkedList.add(new ApiGetFileInfoCtrlPlugin());
        linkedList.add(new OPCallTranslateActivityPlugin());
        linkedList.add(new OPLifecyclePlugin());
        linkedList.add(new ApiMkDirCtrlPlugin());
        linkedList.add(new ApiRmDirCtrlPlugin());
        linkedList.add(new ApiStatCtrlPlugin());
        linkedList.add(new GetSecurityInfoPlugin());
        linkedList.add(new GetTriggerContextHandlerPlugin());
        linkedList.add(new OPTransferMessagePlugin());
        linkedList.add(new PadDisplayScalePlugin());
        return linkedList;
    }

    /* renamed from: c */
    public static List<AbstractC25937e> m89092c() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new ApiHideTabBarPlugin());
        linkedList.add(new ApiHideTabBarRedDotPlugin());
        linkedList.add(new ApiRemoveTabBarBadgePlugin());
        linkedList.add(new AddTabBarItemPlugin());
        linkedList.add(new ApiSetTabbarBadgePlugin());
        linkedList.add(new ApiSetTabBarItemPlugin());
        linkedList.add(new ApiSetTabBarStylePlugin());
        linkedList.add(new ApiShowTabBarPlugin());
        linkedList.add(new ApiShowTabBarRedDotPlugin());
        linkedList.add(new ApiApplyUpdatePlugin());
        linkedList.add(new C24656b());
        linkedList.add(new ApiOpenModalWebViewCtrlPlugin());
        linkedList.add(new ApiOperateModalWebViewStateCtrlPlugin());
        linkedList.add(new ApiHideHomeButtonCtrlPlugin());
        linkedList.add(new ApiHideNavigationBarLoadingCtrlPlugin());
        linkedList.add(new ApiSetNavigationBarColorPlugin());
        linkedList.add(new ApiSetNavigationBarTitlePlugin());
        linkedList.add(new ApiShowNavigationBarLoadingCtrlPlugin());
        linkedList.add(new C25381d());
        linkedList.add(new C24659c());
        linkedList.add(new C25386g());
        linkedList.add(new ApiHideShareMenuCtrlPlugin());
        linkedList.add(new KeyboardPlugin());
        linkedList.add(new C25471a());
        linkedList.add(new C25472b());
        linkedList.add(new ApiReportTimeLinePointsCtrlPlugin());
        linkedList.add(new ShowErrorPagePlugin());
        linkedList.add(new GetTimingSettingPlugin());
        linkedList.add(new ApiSetMenuButtonVisibilityCtrlPlugin());
        linkedList.add(new C25329aa());
        linkedList.add(new ApiPreloadMiniProgramCtrlPlugin());
        linkedList.add(new ApiShowMorePanelCtrlPlugin());
        linkedList.add(new ApiShowShareMenuCtrlPlugin());
        linkedList.add(new ApiStartPullDownRefreshCtrlPlugin());
        linkedList.add(new ApiStopPullDownRefreshCtrlPlugin());
        linkedList.add(new C25330ab());
        linkedList.add(new LarkApiDisablePullDownRefreshCtrlPlugin());
        linkedList.add(new LarkApiEnablePullDownRefreshCtrlPlugin());
        linkedList.add(new RemoveTabBarItemPlugin());
        linkedList.add(new OPGadgetLifecyclePlugin());
        linkedList.add(new OPKillGadgetPlugin());
        linkedList.add(new OnBackPressPlugin());
        linkedList.add(new CreateWorkerPlugin());
        return linkedList;
    }

    /* renamed from: e */
    private static List<AbstractC25937e> m89094e() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new EnterProfileAsyncHandlerPlugin());
        linkedList.add(new ExitMiniProgramPlugin());
        linkedList.add(new ApiAuthorizePlugin());
        linkedList.add(new ApiEnableAccelerometerPlugin());
        linkedList.add(new C24876b());
        linkedList.add(new GetSystemInfoPlugin());
        linkedList.add(new C25011l());
        linkedList.add(new ApiDocsPickerPlugin());
        linkedList.add(new ApiFilePickerPlugin());
        linkedList.add(new RemoveSavedFilePlugin());
        linkedList.add(new OpenDocumentAsyncHandlerPlugin());
        linkedList.add(new C24968h());
        linkedList.add(new GetLocationAsyncHandlerPlugin());
        linkedList.add(new ChooseVideoHandlerPlugin());
        linkedList.add(new CompressImageHandlerPlugin());
        linkedList.add(new GetImageInfoHandlerPlugin());
        linkedList.add(new PreviewImageHandlerPlugin());
        linkedList.add(new SaveImageToPhotosAlbumHandlerPlugin());
        linkedList.add(new SaveVideoToPhotosAlbumHandlerPlugin());
        linkedList.add(new ApiMonitorReportHandlerPlugin());
        linkedList.add(new CreateDownloadFileTaskSyncHandlerPlugin());
        linkedList.add(new GetNetWorkTypeAsyncPlugin());
        linkedList.add(new GetNetworkQualityTypeAsyncPlugin());
        linkedList.add(new NetworkQualityChangeAsyncPlugin());
        linkedList.add(new OperateDownloadFileTaskAsyncHandlerPlugin());
        linkedList.add(new NfcCloseAsyncPlugin());
        linkedList.add(new NfcConnectAsyncPlugin());
        linkedList.add(new NfcGetAtqaAsyncPlugin());
        linkedList.add(new NfcGetSakAsyncPlugin());
        linkedList.add(new NfcMaxTransAsyncPlugin());
        linkedList.add(new NfcSetTimeoutAsyncPlugin());
        linkedList.add(new NfcStartDiscoveryAsyncPlugin());
        linkedList.add(new NfcStopDiscoveryAsyncPlugin());
        linkedList.add(new NfcTransceiveAsyncPlugin());
        linkedList.add(new GetActionMessageInfoPlugin());
        linkedList.add(new CheckWatermarkPlugin());
        linkedList.add(new ApiGetSettingPlugin());
        linkedList.add(new ApiOpenSettingPlugin());
        linkedList.add(new ClearStoragePlugin());
        linkedList.add(new GetStorageInfoPlugin());
        linkedList.add(new GetStoragePlugin());
        linkedList.add(new RemoveStoragePlugin());
        linkedList.add(new SetStoragePlugin());
        linkedList.add(new SetStoragePlugin());
        linkedList.add(new SetKeepScreenOnPlugin());
        linkedList.add(new CheckSessionAsyncPlugin());
        linkedList.add(new GetUserInfoAsyncHandlerPlugin());
        linkedList.add(new OpenSchemaAsyncHandlerPlugin());
        linkedList.add(new ApiStartPasswordVerifyPlugin());
        linkedList.add(new C24425b());
        linkedList.add(new C24427c());
        linkedList.add(new C25250a());
        linkedList.add(new ApiSendMsgCardPlugin());
        linkedList.add(new InspireCloudHandlerPlugin());
        linkedList.add(new UpdateBadgeHandlerPlugin());
        linkedList.add(new ReportBadgeHandlerPlugin());
        linkedList.add(new GetTenantAppScopesAsyncHandlerPlugin());
        linkedList.add(new ApplyTenantAppScopeAsyncHandlerPlugin());
        linkedList.add(new H5ApiGetEnvironmentVariablePlugin());
        return linkedList;
    }

    /* renamed from: f */
    private static List<AbstractC25937e> m89095f() {
        LinkedList linkedList = new LinkedList();
        linkedList.add(new Base64ToTempFilePathPlugin());
        linkedList.add(new C25116b());
        linkedList.add(new ApiChooseLocationCtrlPlugin());
        linkedList.add(new C24912m("mkdir"));
        linkedList.add(new C24912m("rmdir"));
        linkedList.add(new C24912m("stat"));
        linkedList.add(new ApiGetSavedFileInfoPlugin());
        linkedList.add(new C25449a());
        linkedList.add(new ApiSystemLogCtrlPlugin());
        linkedList.add(new ApiConsoleLogOutputPlugin());
        linkedList.add(new ApiLogCtrlPlugin());
        linkedList.add(new C25008i());
        linkedList.add(new LarkApiChooseContactPlugin());
        linkedList.add(new LarkApiGetServerTimePlugin());
        linkedList.add(new C25474d());
        linkedList.add(new LarkApiOpenLocationCtrlPlugin());
        linkedList.add(new C24581b());
        linkedList.add(new C24933e());
        linkedList.add(new LarkApiGetLocationStatusPlugin());
        linkedList.add(new C25379c());
        linkedList.add(new C24932d());
        linkedList.add(new OperateUploadTaskPlugin());
        linkedList.add(new C25429w());
        linkedList.add(new ApiRemoveRecentAppsCtrlPlugin());
        linkedList.add(new ApiCreateAudioInstanceCtrlPlugin());
        linkedList.add(new ApiDestroyAudioInstanceCtrlPlugin());
        linkedList.add(new ApiGetAudioStateCtrlPlugin());
        linkedList.add(new ApiOperateAudioCtrlPlugin());
        linkedList.add(new ApiSetAudioStatePlugin());
        linkedList.add(new ApiGetBgAudioContextCtrlPlugin());
        linkedList.add(new ApiGetBgAudioStateCtrlPlugin());
        linkedList.add(new ApiOperateBgAudioCtrlPlugin());
        linkedList.add(new ApiSetBgAudioCtrlPlugin());
        linkedList.add(new ApiErrorLogCtrlPlugin());
        linkedList.add(new ApiGetHostLaunchQueryPlugin());
        linkedList.add(new C24929b());
        linkedList.add(new ApiReportJsRuntimeErrorCtrlPlugin());
        return linkedList;
    }
}
