package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.AbstractC21635e;
import com.google.android.gms.common.api.AbstractC21641i;
import com.google.android.gms.common.api.AbstractC21692j;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

public final class bl<R extends AbstractC21641i> extends AbstractC21635e<R> {

    /* renamed from: a */
    private final Status f52708a;

    /* access modifiers changed from: package-private */
    /* renamed from: d */
    public final Status mo73395d() {
        return this.f52708a;
    }

    @Override // com.google.android.gms.common.api.AbstractC21635e
    /* renamed from: a */
    public final R mo73289a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC21635e
    /* renamed from: a */
    public final void mo73290a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC21635e
    /* renamed from: b */
    public final boolean mo73293b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC21635e
    /* renamed from: a */
    public final void mo73292a(AbstractC21692j<? super R> jVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC21635e
    /* renamed from: a */
    public final void mo73291a(AbstractC21635e.AbstractC21636a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC21635e
    /* renamed from: c */
    public final Integer mo73294c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
